apiVersion: 1

groups:
  - name: eudiplo-session-alerts
    orgId: 1
    folder: alerting
    interval: 5m
    rules:
      - uid: high-session-error-rate
        title: High Session Error Rate
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: rate(sessions_total{status="error"}[5m])
              interval: ''
              refId: A
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: rate(sessions_total{status=~"success|error"}[5m])
              interval: ''
              refId: B
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.1
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A / B
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: math
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: 'Session error rate is {{ printf "%.2f" $values.C.Value }}% for tenant {{ $labels.tenant_id }}'
          summary: High session error rate detected
        labels:
          severity: warning
          team: eudiplo
