coverage:
  status:
    project:
      default:
        target: 10%
        threshold: 1%
        paths:
          - apps/backend/**
    patch:
      default:
        target: 10%
        paths:
          - apps/backend/**

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "test/"
  - "docs/"
  - "*.config.ts"
  - "*.config.js"
  - "src/main.ts"
  - "dist/"
  - "apps/client/**"
  - "apps/dcapi/**"
  - "apps/webhook/**"  
  - "apps/tmp/**"
  - "monitor/**"
  - "packages/**"
  - "deployment/**"
  - "scripts/**"
  - "schemas/**"
  - "assets/**"
