coverage:
  status:
    project:
      default:
        target: 10%
        threshold: 1%
    patch:
      default:
        target: 10%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "test/"
  - "docs/"
  - "*.config.ts"
  - "*.config.js"
  - "src/main.ts"
  - "dist/"
