services:
  eudiplo:
    image: ghcr.io/openwallet-foundation-labs/eudiplo:latest
    restart: always
    build:
      target: eudiplo
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./assets:/app/config
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  eudiplo-client:
    image: ghcr.io/openwallet-foundation-labs/eudiplo-client:latest
    restart: always
    build:
      target: client
    ports:
      - '4200:80'
    depends_on:
      eudiplo:
        condition: service_healthy
    environment:
      - API_BASE_URL=http://eudiplo:3010
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
