services:
    EUDIPLO:
        image: ghcr.io/openwallet-foundation-labs/eudiplo:latest
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - '3000:3000'
        volumes:
            - ./assets:/app/config
