services:
  EUDIPLO:
    image: ghcr.io/openwallet-foundation-labs/eudiplo:latest
    restart: always
    build:
      context: ./
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./apps/api/assets:/app/assets
