packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - sqlite3

syncInjectedDepsAfterScripts:
  - build
