packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - cbor-extract
  - cpu-features
  - esbuild
  - lmdb
  - msgpackr-extract
  - protobufjs
  - sharp
  - sqlite3
  - ssh2
  - workerd

syncInjectedDepsAfterScripts:
  - build
