packages:
  - 'apps/*'
syncInjectedDepsAfterScripts:
- build
injectWorkspacePackages: true  
onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - sqlite3
