packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - sqlite3

patchedDependencies:
  '@sd-jwt/core': patches/@sd-jwt__core.patch

syncInjectedDepsAfterScripts:
  - build
