services:
  eudiplo:
    image: ghcr.io/openwallet-foundation-labs/eudiplo:latest
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./config:/app/assets

volumes:
  eudiplo-config:
    driver: local
