global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # EUDIPLO service metrics (containerized)
  - job_name: 'eudiplo-docker'
    static_configs:
      - targets: ['eudiplo:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # EUDIPLO service metrics (local development)
  - job_name: 'eudiplo-local'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    # This job will fail when local app is not running, which is fine

# Alerting configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093
