apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eudiplo
resources:
  - namespace.yaml
  - eudiplo-deployment.yaml
  - eudiplo-service.yaml
  - eudiplo-client-deployment.yaml
  - eudiplo-client-service.yaml
  - ingress.yaml
