// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AppControllerMainData,
  AppControllerMainResponses,
  AuthControllerGetGlobalJwksData,
  AuthControllerGetGlobalJwksResponses,
  AuthControllerGetOAuth2TokenData,
  AuthControllerGetOAuth2TokenErrors,
  AuthControllerGetOAuth2TokenResponses,
  AuthControllerGetOidcDiscoveryData,
  AuthControllerGetOidcDiscoveryResponses,
  AuthorizeControllerAuthorizationChallengeEndpointData,
  AuthorizeControllerAuthorizationChallengeEndpointResponses,
  AuthorizeControllerAuthorizeData,
  AuthorizeControllerAuthorizeResponses,
  AuthorizeControllerParData,
  AuthorizeControllerParResponses,
  AuthorizeControllerTokenData,
  AuthorizeControllerTokenResponses,
  CacheControllerClearAllCachesData,
  CacheControllerClearAllCachesResponses,
  CacheControllerClearStatusListCacheData,
  CacheControllerClearStatusListCacheResponses,
  CacheControllerClearTrustListCacheData,
  CacheControllerClearTrustListCacheResponses,
  CacheControllerGetStatsData,
  CacheControllerGetStatsResponses,
  CertControllerAddCertificateData,
  CertControllerAddCertificateResponses,
  CertControllerDeleteCertificateData,
  CertControllerDeleteCertificateResponses,
  CertControllerExportConfigData,
  CertControllerExportConfigResponses,
  CertControllerGetCertificateData,
  CertControllerGetCertificateResponses,
  CertControllerGetCertificatesData,
  CertControllerGetCertificatesResponses,
  CertControllerUpdateCertificateData,
  CertControllerUpdateCertificateResponses,
  ClientControllerCreateClientData,
  ClientControllerCreateClientResponses,
  ClientControllerDeleteClientData,
  ClientControllerDeleteClientResponses,
  ClientControllerGetClientData,
  ClientControllerGetClientResponses,
  ClientControllerGetClientsData,
  ClientControllerGetClientSecretData,
  ClientControllerGetClientSecretResponses,
  ClientControllerGetClientsResponses,
  ClientControllerRotateClientSecretData,
  ClientControllerRotateClientSecretResponses,
  ClientControllerUpdateClientData,
  ClientControllerUpdateClientResponses,
  CredentialConfigControllerDeleteIssuanceConfigurationData,
  CredentialConfigControllerDeleteIssuanceConfigurationResponses,
  CredentialConfigControllerGetConfigByIdData,
  CredentialConfigControllerGetConfigByIdResponses,
  CredentialConfigControllerGetConfigsData,
  CredentialConfigControllerGetConfigsResponses,
  CredentialConfigControllerStoreCredentialConfigurationData,
  CredentialConfigControllerStoreCredentialConfigurationResponses,
  CredentialConfigControllerUpdateCredentialConfigurationData,
  CredentialConfigControllerUpdateCredentialConfigurationResponses,
  CredentialOfferControllerGetOfferData,
  CredentialOfferControllerGetOfferResponses,
  DeferredControllerCompleteDeferredData,
  DeferredControllerCompleteDeferredErrors,
  DeferredControllerCompleteDeferredResponses,
  DeferredControllerFailDeferredData,
  DeferredControllerFailDeferredErrors,
  DeferredControllerFailDeferredResponses,
  HealthControllerCheckData,
  HealthControllerCheckErrors,
  HealthControllerCheckResponses,
  InteractiveAuthorizationControllerCompleteWebAuthData,
  InteractiveAuthorizationControllerCompleteWebAuthErrors,
  InteractiveAuthorizationControllerCompleteWebAuthResponses,
  InteractiveAuthorizationControllerInteractiveAuthorizationData,
  InteractiveAuthorizationControllerInteractiveAuthorizationErrors,
  InteractiveAuthorizationControllerInteractiveAuthorizationResponses,
  IssuanceConfigControllerGetIssuanceConfigurationsData,
  IssuanceConfigControllerGetIssuanceConfigurationsResponses,
  IssuanceConfigControllerStoreIssuanceConfigurationData,
  IssuanceConfigControllerStoreIssuanceConfigurationResponses,
  KeyControllerAddKeyData,
  KeyControllerAddKeyResponses,
  KeyControllerDeleteKeyData,
  KeyControllerDeleteKeyResponses,
  KeyControllerGetKeyData,
  KeyControllerGetKeyResponses,
  KeyControllerGetKeysData,
  KeyControllerGetKeysResponses,
  KeyControllerUpdateKeyData,
  KeyControllerUpdateKeyResponses,
  Oid4VciControllerCredentialData,
  Oid4VciControllerCredentialResponses,
  Oid4VciControllerDeferredCredentialData,
  Oid4VciControllerDeferredCredentialResponses,
  Oid4VciControllerNonceData,
  Oid4VciControllerNonceResponses,
  Oid4VciControllerNotificationsData,
  Oid4VciControllerNotificationsResponses,
  Oid4VciMetadataControllerVctData,
  Oid4VciMetadataControllerVctResponses,
  Oid4VpControllerGetPostRequestWithSessionData,
  Oid4VpControllerGetPostRequestWithSessionResponses,
  Oid4VpControllerGetRequestNoRedirectWithSessionData,
  Oid4VpControllerGetRequestNoRedirectWithSessionResponses,
  Oid4VpControllerGetRequestWithSessionData,
  Oid4VpControllerGetRequestWithSessionResponses,
  Oid4VpControllerGetResponseData,
  Oid4VpControllerGetResponseResponses,
  PresentationManagementControllerConfigurationData,
  PresentationManagementControllerConfigurationResponses,
  PresentationManagementControllerDeleteConfigurationData,
  PresentationManagementControllerDeleteConfigurationResponses,
  PresentationManagementControllerGetConfigurationData,
  PresentationManagementControllerGetConfigurationResponses,
  PresentationManagementControllerStorePresentationConfigData,
  PresentationManagementControllerStorePresentationConfigResponses,
  PresentationManagementControllerUpdateConfigurationData,
  PresentationManagementControllerUpdateConfigurationResponses,
  PrometheusControllerIndexData,
  PrometheusControllerIndexResponses,
  RegistrarControllerCreateAccessCertificateData,
  RegistrarControllerCreateAccessCertificateErrors,
  RegistrarControllerCreateAccessCertificateResponses,
  RegistrarControllerCreateConfigData,
  RegistrarControllerCreateConfigErrors,
  RegistrarControllerCreateConfigResponses,
  RegistrarControllerDeleteConfigData,
  RegistrarControllerDeleteConfigResponses,
  RegistrarControllerGetConfigData,
  RegistrarControllerGetConfigErrors,
  RegistrarControllerGetConfigResponses,
  RegistrarControllerUpdateConfigData,
  RegistrarControllerUpdateConfigErrors,
  RegistrarControllerUpdateConfigResponses,
  SessionConfigControllerGetConfigData,
  SessionConfigControllerGetConfigResponses,
  SessionConfigControllerResetConfigData,
  SessionConfigControllerResetConfigResponses,
  SessionConfigControllerUpdateConfigData,
  SessionConfigControllerUpdateConfigResponses,
  SessionControllerDeleteSessionData,
  SessionControllerDeleteSessionResponses,
  SessionControllerGetAllSessionsData,
  SessionControllerGetAllSessionsResponses,
  SessionControllerGetSessionData,
  SessionControllerGetSessionResponses,
  SessionControllerRevokeAllData,
  SessionControllerRevokeAllResponses,
  StatusListConfigControllerGetConfigData,
  StatusListConfigControllerGetConfigResponses,
  StatusListConfigControllerResetConfigData,
  StatusListConfigControllerResetConfigResponses,
  StatusListConfigControllerUpdateConfigData,
  StatusListConfigControllerUpdateConfigResponses,
  StatusListControllerGetListData,
  StatusListControllerGetListResponses,
  StatusListControllerGetStatusListAggregationData,
  StatusListControllerGetStatusListAggregationResponses,
  StatusListManagementControllerCreateListData,
  StatusListManagementControllerCreateListResponses,
  StatusListManagementControllerDeleteListData,
  StatusListManagementControllerDeleteListResponses,
  StatusListManagementControllerGetListData,
  StatusListManagementControllerGetListResponses,
  StatusListManagementControllerGetListsData,
  StatusListManagementControllerGetListsResponses,
  StatusListManagementControllerUpdateListData,
  StatusListManagementControllerUpdateListResponses,
  StorageControllerDownloadData,
  StorageControllerDownloadResponses,
  StorageControllerUploadData,
  StorageControllerUploadResponses,
  TenantControllerDeleteTenantData,
  TenantControllerDeleteTenantResponses,
  TenantControllerGetTenantData,
  TenantControllerGetTenantResponses,
  TenantControllerGetTenantsData,
  TenantControllerGetTenantsResponses,
  TenantControllerInitTenantData,
  TenantControllerInitTenantResponses,
  TenantControllerUpdateTenantData,
  TenantControllerUpdateTenantResponses,
  TrustListControllerCreateTrustListData,
  TrustListControllerCreateTrustListResponses,
  TrustListControllerDeleteTrustListData,
  TrustListControllerDeleteTrustListResponses,
  TrustListControllerExportTrustListData,
  TrustListControllerExportTrustListResponses,
  TrustListControllerGetAllTrustListsData,
  TrustListControllerGetAllTrustListsResponses,
  TrustListControllerGetTrustListData,
  TrustListControllerGetTrustListResponses,
  TrustListControllerGetTrustListVersionData,
  TrustListControllerGetTrustListVersionResponses,
  TrustListControllerGetTrustListVersionsData,
  TrustListControllerGetTrustListVersionsResponses,
  TrustListControllerUpdateTrustListData,
  TrustListControllerUpdateTrustListResponses,
  TrustListPublicControllerGetTrustListJwtData,
  TrustListPublicControllerGetTrustListJwtResponses,
  VerifierOfferControllerGetOfferData,
  VerifierOfferControllerGetOfferResponses,
  WellKnownControllerAuthzMetadata0Data,
  WellKnownControllerAuthzMetadata0Responses,
  WellKnownControllerAuthzMetadata1Data,
  WellKnownControllerAuthzMetadata1Responses,
  WellKnownControllerGetJwks0Data,
  WellKnownControllerGetJwks0Responses,
  WellKnownControllerGetJwks1Data,
  WellKnownControllerGetJwks1Responses,
  WellKnownControllerIssuerMetadata0Data,
  WellKnownControllerIssuerMetadata0Responses,
  WellKnownControllerIssuerMetadata1Data,
  WellKnownControllerIssuerMetadata1Responses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Main endpoint providing service info
 */
export const appControllerMain = <ThrowOnError extends boolean = true>(
  options?: Options<AppControllerMainData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AppControllerMainResponses,
    unknown,
    ThrowOnError
  >({ url: "/", ...options });

/**
 * Endpoint to check the health of the service.
 */
export const healthControllerCheck = <ThrowOnError extends boolean = true>(
  options?: Options<HealthControllerCheckData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthControllerCheckResponses,
    HealthControllerCheckErrors,
    ThrowOnError
  >({ url: "/health", ...options });

export const prometheusControllerIndex = <ThrowOnError extends boolean = true>(
  options?: Options<PrometheusControllerIndexData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PrometheusControllerIndexResponses,
    unknown,
    ThrowOnError
  >({ url: "/metrics", ...options });

/**
 * OAuth2 Token endpoint - supports client credentials flow only
 * Accepts client credentials either in Authorization header (Basic auth) or request body
 */
export const authControllerGetOAuth2Token = <
  ThrowOnError extends boolean = true,
>(
  options: Options<AuthControllerGetOAuth2TokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthControllerGetOAuth2TokenResponses,
    AuthControllerGetOAuth2TokenErrors,
    ThrowOnError
  >({
    url: "/oauth2/token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * OIDC Discovery Configuration
 *
 * Returns the OpenID Connect discovery configuration for client credentials authentication.
 */
export const authControllerGetOidcDiscovery = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<AuthControllerGetOidcDiscoveryData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AuthControllerGetOidcDiscoveryResponses,
    unknown,
    ThrowOnError
  >({ url: "/.well-known/oauth-authorization-server", ...options });

/**
 * JSON Web Key Set
 *
 * Returns the JSON Web Key Set for token verification.
 */
export const authControllerGetGlobalJwks = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<AuthControllerGetGlobalJwksData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AuthControllerGetGlobalJwksResponses,
    unknown,
    ThrowOnError
  >({ url: "/.well-known/jwks.json", ...options });

/**
 * Get all tenants
 */
export const tenantControllerGetTenants = <ThrowOnError extends boolean = true>(
  options?: Options<TenantControllerGetTenantsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TenantControllerGetTenantsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/tenant",
    ...options,
  });

/**
 * Initialize a tenant
 */
export const tenantControllerInitTenant = <ThrowOnError extends boolean = true>(
  options: Options<TenantControllerInitTenantData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TenantControllerInitTenantResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/tenant",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Deletes a tenant by ID
 */
export const tenantControllerDeleteTenant = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TenantControllerDeleteTenantData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    TenantControllerDeleteTenantResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/tenant/{id}",
    ...options,
  });

/**
 * Get a tenant by ID
 */
export const tenantControllerGetTenant = <ThrowOnError extends boolean = true>(
  options: Options<TenantControllerGetTenantData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TenantControllerGetTenantResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/tenant/{id}",
    ...options,
  });

/**
 * Update a tenant by ID
 */
export const tenantControllerUpdateTenant = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TenantControllerUpdateTenantData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    TenantControllerUpdateTenantResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/tenant/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all clients for a user
 */
export const clientControllerGetClients = <ThrowOnError extends boolean = true>(
  options?: Options<ClientControllerGetClientsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ClientControllerGetClientsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/client",
    ...options,
  });

/**
 * Create a new client
 */
export const clientControllerCreateClient = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ClientControllerCreateClientData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ClientControllerCreateClientResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/client",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a client by its id
 */
export const clientControllerDeleteClient = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ClientControllerDeleteClientData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ClientControllerDeleteClientResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/client/{id}",
    ...options,
  });

/**
 * Get a client by its id
 */
export const clientControllerGetClient = <ThrowOnError extends boolean = true>(
  options: Options<ClientControllerGetClientData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ClientControllerGetClientResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/client/{id}",
    ...options,
  });

/**
 * Update a client by its id
 */
export const clientControllerUpdateClient = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ClientControllerUpdateClientData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    ClientControllerUpdateClientResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/client/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const clientControllerGetClientSecret = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ClientControllerGetClientSecretData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ClientControllerGetClientSecretResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/client/{id}/secret",
    ...options,
  });

/**
 * Rotate (regenerate) a client's secret.
 * Returns the new secret for one-time display - save it immediately!
 *
 * Users with `tenants:manage` role can rotate secrets for any client.
 * Users with `clients:manage` role can only rotate secrets for clients in their tenant.
 */
export const clientControllerRotateClientSecret = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ClientControllerRotateClientSecretData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ClientControllerRotateClientSecretResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/client/{id}/rotate-secret",
    ...options,
  });

/**
 * Get all keys for the tenant.
 */
export const keyControllerGetKeys = <ThrowOnError extends boolean = true>(
  options?: Options<KeyControllerGetKeysData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    KeyControllerGetKeysResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/key",
    ...options,
  });

/**
 * Add a new key to the key service.
 */
export const keyControllerAddKey = <ThrowOnError extends boolean = true>(
  options: Options<KeyControllerAddKeyData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    KeyControllerAddKeyResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/key",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a key from the key service.
 */
export const keyControllerDeleteKey = <ThrowOnError extends boolean = true>(
  options: Options<KeyControllerDeleteKeyData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    KeyControllerDeleteKeyResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/key/{id}",
    ...options,
  });

/**
 * Get a specific key by ID
 */
export const keyControllerGetKey = <ThrowOnError extends boolean = true>(
  options: Options<KeyControllerGetKeyData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    KeyControllerGetKeyResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/key/{id}",
    ...options,
  });

/**
 * Updates an existing key in the key service.
 */
export const keyControllerUpdateKey = <ThrowOnError extends boolean = true>(
  options: Options<KeyControllerUpdateKeyData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    KeyControllerUpdateKeyResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/key/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all certificates for the authenticated tenant.
 * Can be filtered by keyId using query parameter.
 */
export const certControllerGetCertificates = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<CertControllerGetCertificatesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CertControllerGetCertificatesResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/certs",
    ...options,
  });

/**
 * Add a new certificate to a key. If no certificate is provided, a self-signed certificate will be generated.
 */
export const certControllerAddCertificate = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CertControllerAddCertificateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CertControllerAddCertificateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/certs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a certificate.
 */
export const certControllerDeleteCertificate = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CertControllerDeleteCertificateData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CertControllerDeleteCertificateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/certs/{certId}",
    ...options,
  });

/**
 * Get a specific certificate by ID.
 */
export const certControllerGetCertificate = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CertControllerGetCertificateData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CertControllerGetCertificateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/certs/{certId}",
    ...options,
  });

/**
 * Update certificate metadata (description and usage types).
 */
export const certControllerUpdateCertificate = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CertControllerUpdateCertificateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    CertControllerUpdateCertificateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/certs/{certId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Export the configuration of a certificate for import/export purposes.
 */
export const certControllerExportConfig = <ThrowOnError extends boolean = true>(
  options: Options<CertControllerExportConfigData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CertControllerExportConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/certs/{certId}/config",
    ...options,
  });

/**
 * Get the JWT for a specific status list.
 */
export const statusListControllerGetList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<StatusListControllerGetListData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    StatusListControllerGetListResponses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/status-management/status-list/{listId}", ...options });

/**
 * Get all status list URIs
 *
 * Returns a list of all status list token URIs for the tenant. This allows relying parties to pre-fetch all status lists for offline validation. See RFC draft-ietf-oauth-status-list Section 9.
 */
export const statusListControllerGetStatusListAggregation = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    StatusListControllerGetStatusListAggregationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    StatusListControllerGetStatusListAggregationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/{tenantId}/status-management/status-list-aggregation",
    ...options,
  });

/**
 * Reset status list configuration
 *
 * Reset the status list configuration to global defaults. Only affects newly created status lists.
 */
export const statusListConfigControllerResetConfig = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<StatusListConfigControllerResetConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    StatusListConfigControllerResetConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/status-list-config",
    ...options,
  });

/**
 * Get status list configuration
 *
 * Returns the current status list configuration for the tenant. Fields not set use global defaults.
 */
export const statusListConfigControllerGetConfig = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<StatusListConfigControllerGetConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    StatusListConfigControllerGetConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/status-list-config",
    ...options,
  });

/**
 * Update status list configuration
 *
 * Update the status list configuration. Changes only affect newly created status lists. Set a field to null to reset to global default.
 */
export const statusListConfigControllerUpdateConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<StatusListConfigControllerUpdateConfigData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    StatusListConfigControllerUpdateConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/status-list-config",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all status lists
 *
 * Returns all status lists for the tenant, including their capacity and usage.
 */
export const statusListManagementControllerGetLists = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<StatusListManagementControllerGetListsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    StatusListManagementControllerGetListsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/status-lists",
    ...options,
  });

/**
 * Create a status list
 *
 * Creates a new status list. Optionally bind it to a specific credential configuration and/or certificate.
 */
export const statusListManagementControllerCreateList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<StatusListManagementControllerCreateListData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StatusListManagementControllerCreateListResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/status-lists",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a status list
 *
 * Delete a status list. Only allowed if no credentials are using it.
 */
export const statusListManagementControllerDeleteList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<StatusListManagementControllerDeleteListData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    StatusListManagementControllerDeleteListResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/status-lists/{listId}",
    ...options,
  });

/**
 * Get a status list
 *
 * Returns details for a specific status list.
 */
export const statusListManagementControllerGetList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<StatusListManagementControllerGetListData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    StatusListManagementControllerGetListResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/status-lists/{listId}",
    ...options,
  });

/**
 * Update a status list
 *
 * Update a status list's credential configuration binding and/or certificate.
 */
export const statusListManagementControllerUpdateList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<StatusListManagementControllerUpdateListData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    StatusListManagementControllerUpdateListResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/status-lists/{listId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Retrieves all sessions.
 */
export const sessionControllerGetAllSessions = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<SessionControllerGetAllSessionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SessionControllerGetAllSessionsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/session",
    ...options,
  });

/**
 * Deletes a session by its ID
 */
export const sessionControllerDeleteSession = <
  ThrowOnError extends boolean = true,
>(
  options: Options<SessionControllerDeleteSessionData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    SessionControllerDeleteSessionResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/session/{id}",
    ...options,
  });

/**
 * Retrieves the session information for a given session ID.
 */
export const sessionControllerGetSession = <
  ThrowOnError extends boolean = true,
>(
  options: Options<SessionControllerGetSessionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SessionControllerGetSessionResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/session/{id}",
    ...options,
  });

/**
 * Update the status of the credentials of a specific session.
 */
export const sessionControllerRevokeAll = <ThrowOnError extends boolean = true>(
  options: Options<SessionControllerRevokeAllData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SessionControllerRevokeAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/session/revoke",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset session storage configuration
 *
 * Resets the session storage configuration to use global defaults.
 */
export const sessionConfigControllerResetConfig = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<SessionConfigControllerResetConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    SessionConfigControllerResetConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/session-config",
    ...options,
  });

/**
 * Get session storage configuration
 *
 * Returns the session storage configuration for the current tenant.
 */
export const sessionConfigControllerGetConfig = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<SessionConfigControllerGetConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SessionConfigControllerGetConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/session-config",
    ...options,
  });

/**
 * Update session storage configuration
 *
 * Updates the session storage configuration for the current tenant.
 */
export const sessionConfigControllerUpdateConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<SessionConfigControllerUpdateConfigData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    SessionConfigControllerUpdateConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/session-config",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Returns the issuance configurations for this tenant.
 */
export const issuanceConfigControllerGetIssuanceConfigurations = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    IssuanceConfigControllerGetIssuanceConfigurationsData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    IssuanceConfigControllerGetIssuanceConfigurationsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/config",
    ...options,
  });

/**
 * Stores the issuance configuration for this tenant.
 */
export const issuanceConfigControllerStoreIssuanceConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    IssuanceConfigControllerStoreIssuanceConfigurationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    IssuanceConfigControllerStoreIssuanceConfigurationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/config",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Returns the credential configurations for this tenant.
 */
export const credentialConfigControllerGetConfigs = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<CredentialConfigControllerGetConfigsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CredentialConfigControllerGetConfigsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/credentials",
    ...options,
  });

/**
 * Stores the credential configuration for this tenant.
 */
export const credentialConfigControllerStoreCredentialConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    CredentialConfigControllerStoreCredentialConfigurationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    CredentialConfigControllerStoreCredentialConfigurationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/credentials",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Deletes an credential configuration.
 */
export const credentialConfigControllerDeleteIssuanceConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    CredentialConfigControllerDeleteIssuanceConfigurationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    CredentialConfigControllerDeleteIssuanceConfigurationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/credentials/{id}",
    ...options,
  });

/**
 * Returns a specific credential configuration by ID.
 */
export const credentialConfigControllerGetConfigById = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CredentialConfigControllerGetConfigByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CredentialConfigControllerGetConfigByIdResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/credentials/{id}",
    ...options,
  });

/**
 * Updates a credential configuration by ID.
 */
export const credentialConfigControllerUpdateCredentialConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    CredentialConfigControllerUpdateCredentialConfigurationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    CredentialConfigControllerUpdateCredentialConfigurationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/credentials/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Endpoint to issue credentials
 */
export const oid4VciControllerCredential = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Oid4VciControllerCredentialData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    Oid4VciControllerCredentialResponses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/vci/credential", ...options });

/**
 * Deferred Credential Endpoint
 *
 * According to OID4VCI Section 9, this endpoint is used by the wallet to poll
 * for credentials that were not immediately available.
 */
export const oid4VciControllerDeferredCredential = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Oid4VciControllerDeferredCredentialData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    Oid4VciControllerDeferredCredentialResponses,
    unknown,
    ThrowOnError
  >({
    url: "/{tenantId}/vci/deferred_credential",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Notification endpoint
 */
export const oid4VciControllerNotifications = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Oid4VciControllerNotificationsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    Oid4VciControllerNotificationsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/{tenantId}/vci/notification",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const oid4VciControllerNonce = <ThrowOnError extends boolean = true>(
  options: Options<Oid4VciControllerNonceData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    Oid4VciControllerNonceResponses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/vci/nonce", ...options });

/**
 * Endpoint to handle the Authorization Request.
 */
export const authorizeControllerAuthorize = <
  ThrowOnError extends boolean = true,
>(
  options: Options<AuthorizeControllerAuthorizeData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AuthorizeControllerAuthorizeResponses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/authorize", ...options });

/**
 * Endpoint to handle the Pushed Authorization Request (PAR).
 */
export const authorizeControllerPar = <ThrowOnError extends boolean = true>(
  options: Options<AuthorizeControllerParData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthorizeControllerParResponses,
    unknown,
    ThrowOnError
  >({
    url: "/{tenantId}/authorize/par",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Endpoint to validate the token request.
 * This endpoint is used to exchange the authorization code for an access token.
 */
export const authorizeControllerToken = <ThrowOnError extends boolean = true>(
  options: Options<AuthorizeControllerTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthorizeControllerTokenResponses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/authorize/token", ...options });

/**
 * Endpoint for the authorization challenge.
 */
export const authorizeControllerAuthorizationChallengeEndpoint = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    AuthorizeControllerAuthorizationChallengeEndpointData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    AuthorizeControllerAuthorizationChallengeEndpointResponses,
    unknown,
    ThrowOnError
  >({
    url: "/{tenantId}/authorize/challenge",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Interactive Authorization Endpoint
 *
 *
 * Handles interactive authorization requests during credential issuance.
 *
 * **Initial Request:**
 * - Contains `interaction_types_supported` (e.g., "openid4vp_presentation,redirect_to_web")
 * - Response will indicate required interaction (OpenID4VP presentation or web redirect)
 *
 * **Follow-up Request:**
 * - Contains `auth_session` from previous response
 * - Contains `openid4vp_response` (for presentation flow) or `code_verifier` (for web flow)
 * - Response will contain authorization code on success
 *
 */
export const interactiveAuthorizationControllerInteractiveAuthorization = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    InteractiveAuthorizationControllerInteractiveAuthorizationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    InteractiveAuthorizationControllerInteractiveAuthorizationResponses,
    InteractiveAuthorizationControllerInteractiveAuthorizationErrors,
    ThrowOnError
  >({
    url: "/{tenantId}/authorize/interactive",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Complete web authorization
 *
 * Mark a web authorization session as completed after user interaction
 */
export const interactiveAuthorizationControllerCompleteWebAuth = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    InteractiveAuthorizationControllerCompleteWebAuthData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    InteractiveAuthorizationControllerCompleteWebAuthResponses,
    InteractiveAuthorizationControllerCompleteWebAuthErrors,
    ThrowOnError
  >({
    url: "/{tenantId}/authorize/interactive/complete-web-auth/{authSession}",
    ...options,
  });

/**
 * Create an offer for a credential.
 */
export const credentialOfferControllerGetOffer = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CredentialOfferControllerGetOfferData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CredentialOfferControllerGetOfferResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/offer",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Complete a deferred credential transaction
 *
 * Completes a pending deferred credential transaction by providing the claims. The credential will be generated and marked as ready for wallet retrieval.
 */
export const deferredControllerCompleteDeferred = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeferredControllerCompleteDeferredData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DeferredControllerCompleteDeferredResponses,
    DeferredControllerCompleteDeferredErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/deferred/{transactionId}/complete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Fail a deferred credential transaction
 *
 * Marks a deferred credential transaction as failed. The wallet will receive an invalid_transaction_id error when attempting retrieval.
 */
export const deferredControllerFailDeferred = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeferredControllerFailDeferredData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DeferredControllerFailDeferredResponses,
    DeferredControllerFailDeferredErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/issuer/deferred/{transactionId}/fail",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Retrieves the VCT (Verifiable Credential Type) from the credentials service.
 */
export const oid4VciMetadataControllerVct = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Oid4VciMetadataControllerVctData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    Oid4VciMetadataControllerVctResponses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/credentials-metadata/vct/{id}", ...options });

/**
 * Get OpenID4VCI issuer metadata
 *
 * Returns the OpenID4VCI issuer metadata.
 */
export const wellKnownControllerIssuerMetadata0 = <
  ThrowOnError extends boolean = true,
>(
  options: Options<WellKnownControllerIssuerMetadata0Data, ThrowOnError>,
) =>
  (options.client ?? client).get<
    WellKnownControllerIssuerMetadata0Responses,
    unknown,
    ThrowOnError
  >({ url: "/.well-known/openid-credential-issuer/{tenantId}", ...options });

/**
 * Get OpenID4VCI issuer metadata
 *
 * Returns the OpenID4VCI issuer metadata.
 */
export const wellKnownControllerIssuerMetadata1 = <
  ThrowOnError extends boolean = true,
>(
  options: Options<WellKnownControllerIssuerMetadata1Data, ThrowOnError>,
) =>
  (options.client ?? client).get<
    WellKnownControllerIssuerMetadata1Responses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/.well-known/openid-credential-issuer", ...options });

/**
 * Authorization Server Metadata
 */
export const wellKnownControllerAuthzMetadata0 = <
  ThrowOnError extends boolean = true,
>(
  options: Options<WellKnownControllerAuthzMetadata0Data, ThrowOnError>,
) =>
  (options.client ?? client).get<
    WellKnownControllerAuthzMetadata0Responses,
    unknown,
    ThrowOnError
  >({ url: "/.well-known/oauth-authorization-server/{tenantId}", ...options });

/**
 * Authorization Server Metadata
 */
export const wellKnownControllerAuthzMetadata1 = <
  ThrowOnError extends boolean = true,
>(
  options: Options<WellKnownControllerAuthzMetadata1Data, ThrowOnError>,
) =>
  (options.client ?? client).get<
    WellKnownControllerAuthzMetadata1Responses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/.well-known/oauth-authorization-server", ...options });

/**
 * Returns the JSON Web Key Set (JWKS) for the authorization server.
 */
export const wellKnownControllerGetJwks0 = <
  ThrowOnError extends boolean = true,
>(
  options: Options<WellKnownControllerGetJwks0Data, ThrowOnError>,
) =>
  (options.client ?? client).get<
    WellKnownControllerGetJwks0Responses,
    unknown,
    ThrowOnError
  >({ url: "/.well-known/jwks.json/{tenantId}", ...options });

/**
 * Returns the JSON Web Key Set (JWKS) for the authorization server.
 */
export const wellKnownControllerGetJwks1 = <
  ThrowOnError extends boolean = true,
>(
  options: Options<WellKnownControllerGetJwks1Data, ThrowOnError>,
) =>
  (options.client ?? client).get<
    WellKnownControllerGetJwks1Responses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/.well-known/jwks.json", ...options });

/**
 * Returns the authorization request for a given requestId and session.
 */
export const oid4VpControllerGetRequestWithSession = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Oid4VpControllerGetRequestWithSessionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    Oid4VpControllerGetRequestWithSessionResponses,
    unknown,
    ThrowOnError
  >({ url: "/{session}/oid4vp/request", ...options });

/**
 * Returns the authorization request for a given requestId and session.
 */
export const oid4VpControllerGetPostRequestWithSession = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Oid4VpControllerGetPostRequestWithSessionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    Oid4VpControllerGetPostRequestWithSessionResponses,
    unknown,
    ThrowOnError
  >({ url: "/{session}/oid4vp/request", ...options });

/**
 * Returns the authorization request for a given requestId and session, but does not redirect in the end.
 */
export const oid4VpControllerGetRequestNoRedirectWithSession = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    Oid4VpControllerGetRequestNoRedirectWithSessionData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    Oid4VpControllerGetRequestNoRedirectWithSessionResponses,
    unknown,
    ThrowOnError
  >({ url: "/{session}/oid4vp/request/no-redirect", ...options });

/**
 * Endpoint to receive the response from the wallet.
 */
export const oid4VpControllerGetResponse = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Oid4VpControllerGetResponseData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    Oid4VpControllerGetResponseResponses,
    unknown,
    ThrowOnError
  >({
    url: "/{session}/oid4vp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete registrar configuration
 */
export const registrarControllerDeleteConfig = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<RegistrarControllerDeleteConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    RegistrarControllerDeleteConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/registrar/config",
    ...options,
  });

/**
 * Get registrar configuration
 */
export const registrarControllerGetConfig = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<RegistrarControllerGetConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    RegistrarControllerGetConfigResponses,
    RegistrarControllerGetConfigErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/registrar/config",
    ...options,
  });

/**
 * Update registrar configuration
 */
export const registrarControllerUpdateConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<RegistrarControllerUpdateConfigData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    RegistrarControllerUpdateConfigResponses,
    RegistrarControllerUpdateConfigErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/registrar/config",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create or replace registrar configuration
 */
export const registrarControllerCreateConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<RegistrarControllerCreateConfigData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegistrarControllerCreateConfigResponses,
    RegistrarControllerCreateConfigErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/registrar/config",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create an access certificate for a key
 *
 * Creates an access certificate at the registrar for the specified key. Requires a relying party to be already registered at the registrar. The certificate is automatically stored in EUDIPLO.
 */
export const registrarControllerCreateAccessCertificate = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    RegistrarControllerCreateAccessCertificateData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    RegistrarControllerCreateAccessCertificateResponses,
    RegistrarControllerCreateAccessCertificateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/registrar/access-certificate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Returns the presentation request configurations.
 */
export const presentationManagementControllerConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    PresentationManagementControllerConfigurationData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    PresentationManagementControllerConfigurationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/verifier/config",
    ...options,
  });

/**
 * Store a presentation request configuration. If it already exists, it will be updated.
 */
export const presentationManagementControllerStorePresentationConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PresentationManagementControllerStorePresentationConfigData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    PresentationManagementControllerStorePresentationConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/verifier/config",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Deletes a presentation request configuration by its ID.
 */
export const presentationManagementControllerDeleteConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PresentationManagementControllerDeleteConfigurationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    PresentationManagementControllerDeleteConfigurationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/verifier/config/{id}",
    ...options,
  });

/**
 * Get a presentation request configuration by its ID.
 */
export const presentationManagementControllerGetConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PresentationManagementControllerGetConfigurationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    PresentationManagementControllerGetConfigurationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/verifier/config/{id}",
    ...options,
  });

/**
 * Update a presentation request configuration by its ID.
 */
export const presentationManagementControllerUpdateConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PresentationManagementControllerUpdateConfigurationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    PresentationManagementControllerUpdateConfigurationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/verifier/config/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get cache statistics
 *
 * Returns statistics about the trust list and status list caches.
 */
export const cacheControllerGetStats = <ThrowOnError extends boolean = true>(
  options?: Options<CacheControllerGetStatsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CacheControllerGetStatsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cache/stats",
    ...options,
  });

/**
 * Clear all caches
 *
 * Clears both trust list and status list caches. Next verification will fetch fresh data.
 */
export const cacheControllerClearAllCaches = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<CacheControllerClearAllCachesData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    CacheControllerClearAllCachesResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cache",
    ...options,
  });

/**
 * Clear trust list cache
 *
 * Clears the trust list cache. Next verification will fetch fresh trust lists.
 */
export const cacheControllerClearTrustListCache = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<CacheControllerClearTrustListCacheData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    CacheControllerClearTrustListCacheResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cache/trust-list",
    ...options,
  });

/**
 * Clear status list cache
 *
 * Clears the status list (revocation) cache. Next status check will fetch fresh status lists.
 */
export const cacheControllerClearStatusListCache = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<CacheControllerClearStatusListCacheData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    CacheControllerClearStatusListCacheResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cache/status-list",
    ...options,
  });

/**
 * Returns all trust lists for the tenant
 */
export const trustListControllerGetAllTrustLists = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<TrustListControllerGetAllTrustListsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TrustListControllerGetAllTrustListsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/trust-list",
    ...options,
  });

/**
 * Creates a new trust list for the tenant
 */
export const trustListControllerCreateTrustList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TrustListControllerCreateTrustListData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TrustListControllerCreateTrustListResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/trust-list",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Deletes a trust list
 */
export const trustListControllerDeleteTrustList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TrustListControllerDeleteTrustListData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    TrustListControllerDeleteTrustListResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/trust-list/{id}",
    ...options,
  });

/**
 * Returns the trust list by id for the tenant
 */
export const trustListControllerGetTrustList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TrustListControllerGetTrustListData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TrustListControllerGetTrustListResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/trust-list/{id}",
    ...options,
  });

/**
 * Updates a trust list with new entities
 * Creates a new version for audit and regenerates the JWT
 */
export const trustListControllerUpdateTrustList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TrustListControllerUpdateTrustListData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    TrustListControllerUpdateTrustListResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/trust-list/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Exports the trust list in LoTE format
 */
export const trustListControllerExportTrustList = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TrustListControllerExportTrustListData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TrustListControllerExportTrustListResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/trust-list/{id}/export",
    ...options,
  });

/**
 * Returns the version history for a trust list
 */
export const trustListControllerGetTrustListVersions = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TrustListControllerGetTrustListVersionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TrustListControllerGetTrustListVersionsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/trust-list/{id}/versions",
    ...options,
  });

/**
 * Returns a specific version of a trust list
 */
export const trustListControllerGetTrustListVersion = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TrustListControllerGetTrustListVersionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TrustListControllerGetTrustListVersionResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/trust-list/{id}/versions/{versionId}",
    ...options,
  });

/**
 * Returns the JWT of the trust list
 */
export const trustListPublicControllerGetTrustListJwt = <
  ThrowOnError extends boolean = true,
>(
  options: Options<TrustListPublicControllerGetTrustListJwtData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TrustListPublicControllerGetTrustListJwtResponses,
    unknown,
    ThrowOnError
  >({ url: "/{tenantId}/trust-list/{id}", ...options });

/**
 * Create an presentation request that can be sent to the user
 */
export const verifierOfferControllerGetOffer = <
  ThrowOnError extends boolean = true,
>(
  options: Options<VerifierOfferControllerGetOfferData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    VerifierOfferControllerGetOfferResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/verifier/offer",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Upload files that belong to a tenant like images
 */
export const storageControllerUpload = <ThrowOnError extends boolean = true>(
  options: Options<StorageControllerUploadData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StorageControllerUploadResponses,
    unknown,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/storage",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

export const storageControllerDownload = <ThrowOnError extends boolean = true>(
  options: Options<StorageControllerDownloadData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    StorageControllerDownloadResponses,
    unknown,
    ThrowOnError
  >({ url: "/storage/{key}", ...options });
