// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type RoleDto = {
  /**
   * OAuth2 roles
   */
  role:
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "tenants:manage"
    | "registrar:manage";
};

export type ClientCredentialsDto = {
  grant_type?: string;
  client_id: string;
  client_secret: string;
};

export type TokenResponse = {
  access_token: string;
  refresh_token?: string;
  token_type: string;
  expires_in: number;
};

export type ImportTenantDto = {
  /**
   * The name of the tenant.
   */
  name: string;
  /**
   * The description of the tenant.
   */
  description?: string;
};

export type SessionStorageConfig = {
  /**
   * Time-to-live for sessions in seconds. If not set, uses global SESSION_TTL.
   */
  ttlSeconds?: number;
  /**
   * Cleanup mode: 'full' deletes everything, 'anonymize' keeps metadata but removes PII.
   */
  cleanupMode?: "full" | "anonymize";
};

export type StatusListConfig = {
  /**
   * The capacity of the status list. If not set, uses global STATUS_CAPACITY.
   */
  capacity?: number;
  /**
   * Bits per status entry: 1 (valid/revoked), 2 (with suspended), 4/8 (extended). If not set, uses global STATUS_BITS.
   */
  bits?: 1 | 2 | 4 | 8;
  /**
   * TTL in seconds for the status list JWT. If not set, uses global STATUS_TTL.
   */
  ttl?: number;
  /**
   * If true, regenerate JWT immediately on status changes. If false (default), use lazy regeneration on TTL expiry.
   */
  immediateUpdate?: boolean;
  /**
   * If true, include aggregation_uri in status list JWTs for pre-fetching support (default: true).
   */
  enableAggregation?: boolean;
};

export type TenantEntity = {
  /**
   * Session storage configuration for this tenant. Controls TTL and cleanup behavior.
   */
  sessionConfig?: SessionStorageConfig;
  /**
   * Status list configuration for this tenant. Only affects newly created status lists.
   */
  statusListConfig?: StatusListConfig;
  /**
   * The unique identifier for the tenant.
   */
  id: string;
  /**
   * The name of the tenant.
   */
  name: string;
  /**
   * The description of the tenant.
   */
  description?: string;
  /**
   * The current status of the tenant.
   */
  status: string;
  /**
   * The clients associated with the tenant.
   */
  clients: Array<ClientEntity>;
};

export type ClientEntity = {
  /**
   * List of presentation config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedPresentationConfigs?: Array<string>;
  /**
   * List of issuance config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedIssuanceConfigs?: Array<string>;
  /**
   * The unique identifier for the client.
   */
  clientId: string;
  /**
   * The secret key for the client.
   */
  secret?: string;
  /**
   * The unique identifier for the tenant that the client belongs to. Only null for accounts that manage tenants, that do not belong to a client
   */
  tenantId?: string;
  /**
   * The description of the client.
   */
  description?: string;
  /**
   * The roles assigned to the client.
   */
  roles: Array<
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "tenants:manage"
    | "registrar:manage"
  >;
  /**
   * The tenant that the client belongs to.
   */
  tenant?: TenantEntity;
};

export type CreateTenantDto = {
  /**
   * Status list configuration for this tenant. Only affects newly created status lists.
   */
  statusListConfig?: StatusListConfig;
  /**
   * Session storage configuration. Controls TTL and cleanup behavior.
   */
  sessionConfig?: SessionStorageConfig;
  roles?: Array<
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "tenants:manage"
    | "registrar:manage"
  >;
  /**
   * The unique identifier for the tenant.
   */
  id: string;
  /**
   * The name of the tenant.
   */
  name: string;
  /**
   * The description of the tenant.
   */
  description?: string;
};

export type UpdateTenantDto = {
  /**
   * Status list configuration for this tenant. Only affects newly created status lists.
   */
  statusListConfig?: StatusListConfig;
  /**
   * Session storage configuration. Controls TTL and cleanup behavior.
   */
  sessionConfig?: SessionStorageConfig;
  /**
   * The name of the tenant.
   */
  name?: string;
  /**
   * The description of the tenant.
   */
  description?: string;
  roles?: Array<
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "tenants:manage"
    | "registrar:manage"
  >;
};

export type ClientSecretResponseDto = {
  secret: string;
};

export type UpdateClientDto = {
  /**
   * List of presentation config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedPresentationConfigs?: Array<string>;
  /**
   * List of issuance config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedIssuanceConfigs?: Array<string>;
  /**
   * The description of the client.
   */
  description?: string;
  /**
   * The roles assigned to the client.
   */
  roles: Array<
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "tenants:manage"
    | "registrar:manage"
  >;
};

export type CreateClientDto = {
  /**
   * List of presentation config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedPresentationConfigs?: Array<string>;
  /**
   * List of issuance config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedIssuanceConfigs?: Array<string>;
  /**
   * The unique identifier for the client.
   */
  clientId: string;
  /**
   * The secret key for the client.
   */
  secret?: string;
  /**
   * The description of the client.
   */
  description?: string;
  /**
   * The roles assigned to the client.
   */
  roles: Array<
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "tenants:manage"
    | "registrar:manage"
  >;
};

export type StatusListImportDto = {
  /**
   * Unique identifier for the status list
   */
  id: string;
  /**
   * Credential configuration ID to bind this list exclusively to. Leave empty for a shared list.
   */
  credentialConfigurationId?: string;
  /**
   * Key chain ID to use for signing. Leave empty to use the tenant's default StatusList key chain.
   */
  keyChainId?: string;
  /**
   * Capacity of the status list. If not provided, uses tenant or global defaults.
   */
  capacity?: number;
  /**
   * Bits per status value. If not provided, uses tenant or global defaults.
   */
  bits?: 1 | 2 | 4 | 8;
};

export type StatusListAggregationDto = {
  /**
   * Array of status list token URIs
   */
  status_lists: Array<string>;
};

export type UpdateStatusListConfigDto = {
  /**
   * The capacity of the status list. Set to null to reset to global default.
   */
  capacity?: number;
  /**
   * Bits per status entry. Set to null to reset to global default.
   */
  bits?: 1 | 2 | 4 | 8;
  /**
   * TTL in seconds for the status list JWT. Set to null to reset to global default.
   */
  ttl?: number;
  /**
   * If true, regenerate JWT on every status change. Set to null to reset to default (false).
   */
  immediateUpdate?: boolean;
  /**
   * If true, include aggregation_uri in status list JWTs for pre-fetching support. Set to null to reset to default (true).
   */
  enableAggregation?: boolean;
};

export type StatusListResponseDto = {
  /**
   * Unique identifier for the status list
   */
  id: string;
  /**
   * The tenant ID
   */
  tenantId: string;
  /**
   * Credential configuration ID this list is bound to. Null means shared.
   */
  credentialConfigurationId?: string;
  /**
   * Key chain ID used for signing. Null means using the tenant's default.
   */
  keyChainId?: string;
  /**
   * Bits per status value
   */
  bits: 1 | 2 | 4 | 8;
  /**
   * Total capacity of the status list
   */
  capacity: number;
  /**
   * Number of entries in use
   */
  usedEntries: number;
  /**
   * Number of available entries
   */
  availableEntries: number;
  /**
   * The public URI for this status list
   */
  uri: string;
  /**
   * Creation timestamp
   */
  createdAt: string;
  /**
   * JWT expiration timestamp. Null if JWT has not been generated yet.
   */
  expiresAt?: string;
};

export type CreateStatusListDto = {
  /**
   * Credential configuration ID to bind this list exclusively to. Leave empty for a shared list.
   */
  credentialConfigurationId?: string;
  /**
   * Key chain ID to use for signing. Leave empty to use the tenant's default StatusList key chain.
   */
  keyChainId?: string;
  /**
   * Bits per status value. More bits allow more status states. Defaults to tenant configuration.
   */
  bits?: 1 | 2 | 4 | 8;
  /**
   * Maximum number of credential status entries. Defaults to tenant configuration.
   */
  capacity?: number;
};

export type UpdateStatusListDto = {
  /**
   * Credential configuration ID to bind this list exclusively to. Set to null to make this a shared list.
   */
  credentialConfigurationId?: string;
  /**
   * Key chain ID to use for signing. Set to null to use the tenant's default StatusList key chain.
   */
  keyChainId?: string;
};

export type AuthorizeQueries = {
  issuer_state?: string;
  response_type?: string;
  client_id?: string;
  redirect_uri?: string;
  resource?: string;
  scope?: string;
  code_challenge?: string;
  code_challenge_method?: string;
  dpop_jkt?: string;
  request_uri?: string;
  auth_session?: string;
  state?: string;
};

export type OfferRequestDto = {
  /**
   * The type of response expected for the offer request.
   */
  response_type: "uri" | "dc-api";
  /**
   * Credential claims configuration per credential. Keys must match credentialConfigurationIds.
   */
  credentialClaims?: {
    additionalProperties?:
      | {
          type: "inline";
          claims: {
            [key: string]: unknown;
          };
        }
      | {
          type: "attributeProvider";
          attributeProviderId: string;
        }
      | {
          type: "webhook";
          webhook: {
            url: string;
            auth?: {
              [key: string]: unknown;
            };
          };
        };
  };
  /**
   * The flow type for the offer request.
   */
  flow: "authorization_code" | "pre_authorized_code";
  /**
   * Transaction code for pre-authorized code flow.
   */
  tx_code?: string;
  /**
   * Description for the transaction code (e.g., "Please enter the PIN sent to your email").
   */
  tx_code_description?: string;
  /**
   * List of credential configuration ids to be included in the offer.
   */
  credentialConfigurationIds: Array<string>;
  /**
   * Optional authorization server to be used for this issuance flow.
   */
  authorization_server?: string;
  /**
   * ID of the webhook endpoint to notify about the status of the issuance process.
   */
  webhookEndpointId?: string;
};

export type WebHookAuthConfigNone = {
  /**
   * The type of authentication used for the webhook.
   */
  type: "none";
};

export type ApiKeyConfig = {
  /**
   * The name of the header where the API key will be sent.
   */
  headerName: string;
  /**
   * The value of the API key to be sent in the header.
   */
  value: string;
};

export type WebHookAuthConfigHeader = {
  /**
   * The type of authentication used for the webhook.
   */
  type: "apiKey";
  /**
   * Configuration for API key authentication.
   * This is required if the type is 'apiKey'.
   */
  config: ApiKeyConfig;
};

export type WebhookConfig = {
  /**
   * Optional authentication configuration for the webhook.
   * If not provided, no authentication will be used.
   */
  auth: WebHookAuthConfigNone | WebHookAuthConfigHeader;
  /**
   * List of credential IDs to include raw tokens for (e.g., ['sca_credential'])
   */
  includeRawTokensFor?: Array<string>;
  /**
   * The URL to which the webhook will send notifications.
   */
  url: string;
};

export type TransactionData = {
  type: string;
  credential_ids: Array<string>;
};

export type Session = {
  /**
   * Status of the session.
   */
  status: "active" | "fetched" | "completed" | "expired" | "failed";
  /**
   * Unique identifier for the session.
   */
  id: string;
  /**
   * The timestamp when the request was created.
   */
  createdAt: string;
  /**
   * The timestamp when the request was last updated.
   */
  updatedAt: string;
  /**
   * The timestamp when the request is set to expire.
   */
  expiresAt?: string;
  /**
   * Flag indicating whether to use the DC API for the presentation request.
   */
  useDcApi: boolean;
  /**
   * Tenant ID for multi-tenancy support.
   */
  tenantId: string;
  /**
   * The tenant that owns this object.
   */
  tenant: TenantEntity;
  authorization_code?: string;
  /**
   * Request URI from the authorization request.
   */
  request_uri?: string;
  /**
   * Authorization queries associated with the session.
   * Encrypted at rest.
   */
  auth_queries?: AuthorizeQueries;
  /**
   * Credential offer object containing details about the credential offer or presentation request.
   * Encrypted at rest.
   */
  offer?: {
    [key: string]: unknown;
  };
  /**
   * Offer URL for the credential offer.
   */
  offerUrl?: string;
  /**
   * Credential payload containing the offer request details.
   * Encrypted at rest - may contain sensitive claim data.
   */
  credentialPayload?: OfferRequestDto;
  /**
   * ID of the webhook endpoint to notify about issuance status.
   */
  webhookEndpointId?: string;
  /**
   * Notifications associated with the session.
   */
  notifications: Array<{
    [key: string]: unknown;
  }>;
  requestId?: string;
  /**
   * The URL of the presentation auth request.
   */
  requestUrl?: string;
  /**
   * Signed presentation auth request.
   */
  requestObject?: string;
  /**
   * Verified credentials from the presentation process.
   * Encrypted at rest - contains personal information.
   */
  credentials?: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Noncce from the Verifiable Presentation request.
   */
  vp_nonce?: string;
  /**
   * Client ID used in the OID4VP authorization request.
   */
  clientId?: string;
  /**
   * Response URI used in the OID4VP authorization request.
   */
  responseUri?: string;
  /**
   * Redirect URI to which the user-agent should be redirected after the presentation is completed.
   */
  redirectUri?: string;
  /**
   * Where to send the claims webhook response.
   */
  parsedWebhook?: WebhookConfig;
  /**
   * Transaction data to include in the OID4VP authorization request.
   * Can be overridden per-request from the presentation configuration.
   */
  transaction_data?: Array<TransactionData>;
  externalIssuer?: string;
  /**
   * The subject (sub) from the external authorization server token.
   * Used to identify the user at the external AS.
   */
  externalSubject?: string;
  /**
   * Error reason if the session failed.
   * Stores the error message when status is 'failed'.
   */
  errorReason?: string;
};

export type SessionLogEntryResponseDto = {
  /**
   * Log entry ID
   */
  id: string;
  /**
   * Session ID
   */
  sessionId: string;
  /**
   * Timestamp of the log entry
   */
  timestamp: string;
  /**
   * Log level
   */
  level: "info" | "warn" | "error";
  /**
   * Flow stage
   */
  stage?: string;
  /**
   * Log message
   */
  message: string;
  /**
   * Additional structured detail
   */
  detail?: {
    [key: string]: unknown;
  };
};

export type StatusUpdateDto = {
  /**
   * The session ID of the user
   */
  sessionId: string;
  /**
   * The ID of the credential configuration
   * This is optional, if not provided, all credentials will be revoked of the session.
   */
  credentialConfigurationId?: string;
  /**
   * The status of the credential
   * 0 = valid, 1 = revoked, 2 = suspended
   */
  status: number;
};

export type UpdateSessionConfigDto = {
  /**
   * Time-to-live for sessions in seconds. Set to null to use global default.
   */
  ttlSeconds?: number;
  /**
   * Cleanup mode: 'full' deletes everything, 'anonymize' keeps metadata but removes PII.
   */
  cleanupMode?: "full" | "anonymize";
};

export type AuthenticationMethodNone = {
  method: "none";
};

export type AuthenticationUrlConfig = {
  /**
   * The URL used in the OID4VCI authorized code flow.
   * This URL is where users will be redirected for authentication.
   */
  url: string;
  /**
   * Optional webhook configuration for authentication callbacks
   */
  webhook?: WebhookConfig;
};

export type AuthenticationMethodAuth = {
  method: "auth";
  config: AuthenticationUrlConfig;
};

export type PresentationDuringIssuanceConfig = {
  /**
   * Link to the presentation configuration that is relevant for the issuance process
   */
  type: string;
};

export type AuthenticationMethodPresentation = {
  method: "presentationDuringIssuance";
  config: PresentationDuringIssuanceConfig;
};

export type UpstreamOidcConfig = {
  /**
   * The OIDC issuer URL of the upstream provider
   */
  issuer: string;
  /**
   * The client ID registered with the upstream provider
   */
  clientId: string;
  /**
   * The client secret for confidential clients
   */
  clientSecret?: string;
  /**
   * Scopes to request from the upstream provider
   */
  scopes?: Array<string>;
};

export type ChainedAsTokenConfig = {
  /**
   * Access token lifetime in seconds
   */
  lifetimeSeconds?: number;
  /**
   * Key ID for token signing
   */
  signingKeyId?: string;
};

export type ChainedAsConfig = {
  /**
   * Enable chained AS mode
   */
  enabled: boolean;
  /**
   * Upstream OIDC provider configuration
   */
  upstream?: UpstreamOidcConfig;
  /**
   * Token configuration
   */
  token?: ChainedAsTokenConfig;
  /**
   * Require DPoP binding for tokens
   */
  requireDPoP?: boolean;
};

export type DisplayLogo = {
  uri: string;
  alt_text?: string;
};

export type DisplayInfo = {
  name?: string;
  locale?: string;
  logo?: DisplayLogo;
};

export type IssuanceConfig = {
  /**
   * Key ID for signing access tokens. If unset, the default signing key is used.
   */
  signingKeyId?: string;
  /**
   * Configuration for Chained Authorization Server mode.
   * When enabled, EUDIPLO acts as an OAuth AS facade, delegating user authentication
   * to an upstream OIDC provider while issuing its own tokens with issuer_state.
   */
  chainedAs?: ChainedAsConfig;
  /**
   * The tenant that owns this object.
   */
  tenant: TenantEntity;
  /**
   * Authentication server URL for the issuance process.
   */
  authServers?: Array<string>;
  /**
   * Value to determine the amount of credentials that are issued in a batch.
   * Default is 1.
   */
  batchSize?: number;
  /**
   * Indicates whether DPoP is required for the issuance process. Default value is true.
   */
  dPopRequired?: boolean;
  /**
   * Whether refresh tokens should be issued for OID4VCI token responses.
   * Default value is true.
   */
  refreshTokenEnabled?: boolean;
  /**
   * Refresh token lifetime in seconds.
   * Default value is 2592000 (30 days).
   */
  refreshTokenExpiresInSeconds?: number;
  /**
   * Indicates whether wallet attestation is required for the token endpoint.
   * When enabled, wallets must provide OAuth-Client-Attestation headers.
   * Default value is false.
   */
  walletAttestationRequired?: boolean;
  /**
   * URLs of trust lists containing trusted wallet providers.
   * The wallet attestation's X.509 certificate will be validated against these trust lists.
   * If empty and walletAttestationRequired is true, all wallet providers are rejected.
   */
  walletProviderTrustLists?: Array<string>;
  /**
   * The URL of the preferred authorization server for wallet-initiated flows.
   * When set, this AS is placed first in the `authorization_servers` array
   * of the credential issuer metadata, signaling wallets to use it by default.
   * Must match one of the configured auth servers, the chained AS URL, or "built-in".
   */
  preferredAuthServer?: string;
  display: Array<DisplayInfo>;
  /**
   * The timestamp when the VP request was created.
   */
  createdAt: string;
  /**
   * The timestamp when the VP request was last updated.
   */
  updatedAt: string;
};

export type IssuanceDto = {
  /**
   * Key ID for signing access tokens. If unset, the default signing key is used.
   */
  signingKeyId?: string;
  /**
   * Configuration for Chained Authorization Server mode.
   * When enabled, EUDIPLO acts as an OAuth AS facade, delegating user authentication
   * to an upstream OIDC provider while issuing its own tokens with issuer_state.
   */
  chainedAs?: ChainedAsConfig;
  /**
   * Authentication server URL for the issuance process.
   */
  authServers?: Array<string>;
  /**
   * Value to determine the amount of credentials that are issued in a batch.
   * Default is 1.
   */
  batchSize?: number;
  /**
   * Indicates whether DPoP is required for the issuance process. Default value is true.
   */
  dPopRequired?: boolean;
  /**
   * Whether refresh tokens should be issued for OID4VCI token responses.
   * Default value is true.
   */
  refreshTokenEnabled?: boolean;
  /**
   * Refresh token lifetime in seconds.
   * Default value is 2592000 (30 days).
   */
  refreshTokenExpiresInSeconds?: number;
  /**
   * Indicates whether wallet attestation is required for the token endpoint.
   * When enabled, wallets must provide OAuth-Client-Attestation headers.
   * Default value is false.
   */
  walletAttestationRequired?: boolean;
  /**
   * URLs of trust lists containing trusted wallet providers.
   * The wallet attestation's X.509 certificate will be validated against these trust lists.
   * If empty and walletAttestationRequired is true, all wallet providers are rejected.
   */
  walletProviderTrustLists?: Array<string>;
  /**
   * The URL of the preferred authorization server for wallet-initiated flows.
   * When set, this AS is placed first in the `authorization_servers` array
   * of the credential issuer metadata, signaling wallets to use it by default.
   * Must match one of the configured auth servers, the chained AS URL, or "built-in".
   */
  preferredAuthServer?: string;
  display: Array<DisplayInfo>;
};

export type ClaimsQuery = {
  id?: string;
  path: Array<string>;
  values?: Array<string>;
};

export type TrustedAuthorityQuery = {
  type: "aki" | "etsi_tl";
  values: Array<string>;
};

export type CredentialQuery = {
  id: string;
  format: string;
  multiple?: boolean;
  claims?: Array<ClaimsQuery>;
  meta: {
    [key: string]: unknown;
  };
  trusted_authorities?: Array<TrustedAuthorityQuery>;
};

export type CredentialSetQuery = {
  options: Array<Array<string>>;
  required?: boolean;
};

export type PolicyCredential = {
  claims?: Array<ClaimsQuery>;
  credentials: Array<CredentialQuery>;
  credential_sets?: Array<CredentialSetQuery>;
};

export type AttestationBasedPolicy = {
  policy: "attestationBased";
  values: Array<PolicyCredential>;
};

export type NoneTrustPolicy = {
  policy: "none";
};

export type AllowListPolicy = {
  policy: "allowList";
  values: Array<string>;
};

export type RootOfTrustPolicy = {
  policy: "rootOfTrust";
  values: string;
};

export type Vct = {
  vct?: string;
  name?: string;
  description?: string;
  extends?: string;
  "extends#integrity"?: string;
  schema_uri?: string;
  "schema_uri#integrity"?: string;
};

export type IaeActionOpenid4VpPresentation = {
  /**
   * Action type discriminator
   */
  type: "openid4vp_presentation";
  /**
   * Optional label for this step (for display purposes)
   */
  label?: string;
  /**
   * ID of the presentation configuration to use for this step
   */
  presentationConfigId: string;
};

export type IaeActionRedirectToWeb = {
  /**
   * Action type discriminator
   */
  type: "redirect_to_web";
  /**
   * Optional label for this step (for display purposes)
   */
  label?: string;
  /**
   * URL to redirect the user to for web-based interaction
   */
  url: string;
  /**
   * URL where the external service should redirect back after completion. If not provided, the service must call back to the IAE endpoint.
   */
  callbackUrl?: string;
  /**
   * Description of what the user should do on the web page (for wallet display)
   */
  description?: string;
};

export type EmbeddedDisclosurePolicy = {
  policy: string;
};

export type KeyAttestationsRequired = {
  /**
   * List of required key storage types (e.g., iso_18045_high, iso_18045_moderate)
   */
  key_storage?: Array<string>;
  /**
   * List of required user authentication types (e.g., iso_18045_high, iso_18045_moderate)
   */
  user_authentication?: Array<string>;
};

export type DisplayImage = {
  uri: string;
};

export type Display = {
  name: string;
  description: string;
  locale: string;
  background_color?: string;
  text_color?: string;
  background_image?: DisplayImage;
  logo?: DisplayImage;
};

export type ClaimDisplayInfo = {
  /**
   * Human-readable name for the claim
   */
  name?: string;
  /**
   * Locale identifier (e.g., en-US, de-DE)
   */
  locale?: string;
};

export type ClaimMetadata = {
  /**
   * Path to the claim. For SD-JWT: JSONPath-like array. For mDOC: [namespace, claim_name]
   */
  path: Array<string>;
  /**
   * Whether this claim must be disclosed
   */
  mandatory?: boolean;
  /**
   * Display information for the claim in different locales
   */
  display?: Array<ClaimDisplayInfo>;
};

export type IssuerMetadataCredentialConfig = {
  /**
   * Key attestation requirements for JWT proofs for this credential.
   * When set, this is published in proof_types_supported.jwt.key_attestations_required
   * for this specific credential configuration.
   */
  keyAttestationsRequired?: KeyAttestationsRequired;
  format: "mso_mdoc" | "dc+sd-jwt";
  display: Array<Display>;
  scope?: string;
  /**
   * Document type for mDOC credentials (e.g., "org.iso.18013.5.1.mDL").
   * Only applicable when format is "mso_mdoc".
   */
  docType?: string;
  /**
   * Namespace for mDOC credentials (e.g., "org.iso.18013.5.1").
   * Only applicable when format is "mso_mdoc".
   * Used when claims are provided as a flat object.
   */
  namespace?: string;
  /**
   * Claims organized by namespace for mDOC credentials.
   * Allows specifying claims across multiple namespaces.
   * Only applicable when format is "mso_mdoc".
   * Example:
   * {
   * "org.iso.18013.5.1": { "given_name": "John", "family_name": "Doe" },
   * "org.iso.18013.5.1.aamva": { "DHS_compliance": "F" }
   * }
   */
  claimsByNamespace?: {
    [key: string]: unknown;
  };
  /**
   * Claims metadata for wallet rendering.
   * Follows the OID4VCI credential_metadata.claims specification.
   * Each claim includes a path (JSONPath-like array), optional mandatory flag,
   * and display information with multi-language support.
   *
   * Example:
   * [
   * { "path": ["given_name"], "mandatory": false, "display": [{ "name": "Given Name", "locale": "en-US" }] },
   * { "path": ["address", "street_address"], "display": [{ "name": "Street Address", "locale": "en-US" }] }
   * ]
   */
  claimsMetadata?: Array<ClaimMetadata>;
};

export type AttributeProviderEntity = {
  auth: WebHookAuthConfigNone | WebHookAuthConfigHeader;
  id: string;
  tenantId: string;
  tenant: TenantEntity;
  name: string;
  description?: string;
  url: string;
};

export type WebhookEndpointEntity = {
  auth: WebHookAuthConfigNone | WebHookAuthConfigHeader;
  id: string;
  tenantId: string;
  tenant: TenantEntity;
  name: string;
  description?: string;
  url: string;
};

export type KeyChainEntity = {
  /**
   * Unique identifier for the key chain.
   * This is the ID referenced by other entities (e.g., issuance config's signingKeyId).
   */
  id: string;
  /**
   * Tenant ID for the key chain.
   */
  tenantId: string;
  /**
   * The tenant that owns this key chain.
   */
  tenant: TenantEntity;
  /**
   * Human-readable description of the key chain.
   */
  description?: string;
  /**
   * The purpose/role of this key chain in the system.
   */
  usageType: "access" | "attestation" | "trustList" | "statusList" | "encrypt";
  /**
   * The usage type of the keys (sign or encrypt).
   */
  usage: "sign" | "encrypt";
  /**
   * The KMS provider used for this key chain.
   * References a configured KMS provider name.
   */
  kmsProvider: string;
  /**
   * External key identifier for cloud KMS providers.
   * This field stores the provider-specific key reference for the active signing key.
   */
  externalKeyId?: string;
  rootKey?: {
    [key: string]: unknown;
  };
  /**
   * Root CA certificate in PEM format.
   * Self-signed certificate for the root CA key.
   */
  rootCertificate?: string;
  activeKey: {
    [key: string]: unknown;
  };
  /**
   * Certificate for the active signing key in PEM format.
   * Either CA-signed (if rootKey exists) or self-signed.
   */
  activeCertificate: string;
  rotationEnabled: boolean;
  /**
   * Rotation interval in days. Key material will be rotated after this many days.
   */
  rotationIntervalDays?: number;
  /**
   * Certificate validity in days when generating new certificates.
   */
  certValidityDays?: number;
  /**
   * Timestamp of when the key was last rotated.
   */
  lastRotatedAt?: string;
  previousKey?: {
    [key: string]: unknown;
  };
  /**
   * Certificate for the previous signing key in PEM format.
   */
  previousCertificate?: string;
  /**
   * Expiry date for the previous key.
   * After this date, the previous key should be deleted.
   */
  previousKeyExpiry?: string;
  createdAt: string;
  /**
   * The timestamp when the key chain was last updated.
   */
  updatedAt: string;
};

export type SchemaResponse = {
  $schema: string;
  type: string;
  properties: {
    [key: string]: unknown;
  };
  required?: Array<string>;
  title?: string;
  description?: string;
};

export type CredentialConfig = {
  /**
   * VCT as a URI string (e.g., urn:eudi:pid:de:1) or as an object for EUDIPLO-hosted VCT
   */
  vct?: string | Vct;
  /**
   * List of IAE actions to execute before credential issuance
   */
  iaeActions?: Array<IaeActionOpenid4VpPresentation | IaeActionRedirectToWeb>;
  /**
   * Embedded disclosure policy (discriminated union by `policy`).
   * The discriminator makes class-transformer instantiate the right subclass,
   * and then class-validator runs that subclass’s rules.
   */
  embeddedDisclosurePolicy?: EmbeddedDisclosurePolicy;
  id: string;
  description?: string;
  /**
   * The tenant that owns this object.
   */
  tenant: TenantEntity;
  config: IssuerMetadataCredentialConfig;
  claims?: {
    [key: string]: unknown;
  };
  /**
   * Reference to the attribute provider used for fetching claims.
   * Optional: if set, claims will be fetched from this provider during issuance.
   */
  attributeProviderId?: string;
  attributeProvider?: AttributeProviderEntity;
  /**
   * Reference to the webhook endpoint used for notifications.
   * Optional: if set, notifications will be sent to this endpoint.
   */
  webhookEndpointId?: string;
  webhookEndpoint?: WebhookEndpointEntity;
  disclosureFrame?: {
    [key: string]: unknown;
  };
  keyBinding?: boolean;
  /**
   * Reference to the key chain used for signing.
   * Optional: if not specified, the default attestation key chain will be used.
   */
  keyChainId?: string;
  keyChain?: KeyChainEntity;
  statusManagement?: boolean;
  lifeTime?: number;
  schema?: SchemaResponse;
};

export type CredentialConfigCreate = {
  /**
   * VCT as a URI string (e.g., urn:eudi:pid:de:1) or as an object for EUDIPLO-hosted VCT
   */
  vct?: string | Vct;
  /**
   * List of IAE actions to execute before credential issuance
   */
  iaeActions?: Array<IaeActionOpenid4VpPresentation | IaeActionRedirectToWeb>;
  /**
   * Embedded disclosure policy (discriminated union by `policy`).
   * The discriminator makes class-transformer instantiate the right subclass,
   * and then class-validator runs that subclass’s rules.
   */
  embeddedDisclosurePolicy?: EmbeddedDisclosurePolicy;
  id: string;
  description?: string;
  config: IssuerMetadataCredentialConfig;
  claims?: {
    [key: string]: unknown;
  };
  /**
   * Reference to the attribute provider used for fetching claims.
   * Optional: if set, claims will be fetched from this provider during issuance.
   */
  attributeProviderId?: string;
  /**
   * Reference to the webhook endpoint used for notifications.
   * Optional: if set, notifications will be sent to this endpoint.
   */
  webhookEndpointId?: string;
  disclosureFrame?: {
    [key: string]: unknown;
  };
  keyBinding?: boolean;
  /**
   * Reference to the key chain used for signing.
   * Optional: if not specified, the default attestation key chain will be used.
   */
  keyChainId?: string;
  statusManagement?: boolean;
  lifeTime?: number;
  schema?: SchemaResponse;
};

export type CredentialConfigUpdate = {
  /**
   * VCT as a URI string (e.g., urn:eudi:pid:de:1) or as an object for EUDIPLO-hosted VCT
   */
  vct?: string | Vct;
  /**
   * List of IAE actions to execute before credential issuance
   */
  iaeActions?: Array<IaeActionOpenid4VpPresentation | IaeActionRedirectToWeb>;
  /**
   * Embedded disclosure policy (discriminated union by `policy`).
   * The discriminator makes class-transformer instantiate the right subclass,
   * and then class-validator runs that subclass’s rules.
   */
  embeddedDisclosurePolicy?: EmbeddedDisclosurePolicy;
  id?: string;
  description?: string;
  config?: IssuerMetadataCredentialConfig;
  claims?: {
    [key: string]: unknown;
  };
  /**
   * Reference to the attribute provider used for fetching claims.
   * Optional: if set, claims will be fetched from this provider during issuance.
   */
  attributeProviderId?: string;
  /**
   * Reference to the webhook endpoint used for notifications.
   * Optional: if set, notifications will be sent to this endpoint.
   */
  webhookEndpointId?: string;
  disclosureFrame?: {
    [key: string]: unknown;
  };
  keyBinding?: boolean;
  /**
   * Reference to the key chain used for signing.
   * Optional: if not specified, the default attestation key chain will be used.
   */
  keyChainId?: string;
  statusManagement?: boolean;
  lifeTime?: number;
  schema?: SchemaResponse;
};

export type CreateAttributeProviderDto = {
  auth: WebHookAuthConfigNone | WebHookAuthConfigHeader;
  id: string;
  name: string;
  description?: string;
  url: string;
};

export type UpdateAttributeProviderDto = {
  auth?: WebHookAuthConfigNone | WebHookAuthConfigHeader;
  id?: string;
  name?: string;
  description?: string;
  url?: string;
};

export type CreateWebhookEndpointDto = {
  auth: WebHookAuthConfigNone | WebHookAuthConfigHeader;
  id: string;
  name: string;
  description?: string;
  url: string;
};

export type UpdateWebhookEndpointDto = {
  auth?: WebHookAuthConfigNone | WebHookAuthConfigHeader;
  id?: string;
  name?: string;
  description?: string;
  url?: string;
};

export type Dcql = {
  credentials: Array<CredentialQuery>;
  credential_sets?: Array<CredentialSetQuery>;
};

export type RegistrationCertificateRequest = {
  /**
   * The body of the registration certificate request containing the necessary details.
   */
  jwt: string;
};

export type PresentationAttachment = {
  format: string;
  data: {
    [key: string]: unknown;
  };
  credential_ids?: Array<string>;
};

export type PresentationConfig = {
  /**
   * Unique identifier for the VP request.
   */
  id: string;
  /**
   * The tenant that owns this object.
   */
  tenant: TenantEntity;
  /**
   * Description of the presentation configuration.
   */
  description?: string;
  /**
   * Lifetime how long the presentation request is valid after creation, in seconds.
   */
  lifeTime?: number;
  /**
   * The DCQL query to be used for the VP request.
   */
  dcql_query: Dcql;
  transaction_data?: Array<TransactionData>;
  /**
   * The registration certificate request containing the necessary details.
   */
  registrationCert?: RegistrationCertificateRequest;
  /**
   * Optional webhook URL to receive the response.
   */
  webhook?: WebhookConfig;
  /**
   * The timestamp when the VP request was created.
   */
  createdAt: string;
  /**
   * The timestamp when the VP request was last updated.
   */
  updatedAt: string;
  /**
   * Attestation that should be attached
   */
  attached?: Array<PresentationAttachment>;
  /**
   * Redirect URI to which the user-agent should be redirected after the presentation is completed.
   * You can use the `{sessionId}` placeholder in the URI, which will be replaced with the actual session ID.
   */
  redirectUri?: string;
  /**
   * Optional ID of the access certificate to use for signing the presentation request.
   * If not provided, the default access certificate for the tenant will be used.
   *
   * Note: This is intentionally NOT a TypeORM relationship because CertEntity uses
   * a composite primary key (id + tenantId), and SQLite cannot create foreign keys
   * that reference only part of a composite primary key. The relationship is handled
   * at the application level in the service layer.
   */
  accessKeyChainId?: string;
};

export type PresentationConfigCreateDto = {
  /**
   * Unique identifier for the VP request.
   */
  id: string;
  /**
   * Description of the presentation configuration.
   */
  description?: string;
  /**
   * Lifetime how long the presentation request is valid after creation, in seconds.
   */
  lifeTime?: number;
  /**
   * The DCQL query to be used for the VP request.
   */
  dcql_query: Dcql;
  transaction_data?: Array<TransactionData>;
  /**
   * The registration certificate request containing the necessary details.
   */
  registrationCert?: RegistrationCertificateRequest;
  /**
   * Optional webhook URL to receive the response.
   */
  webhook?: WebhookConfig;
  /**
   * Attestation that should be attached
   */
  attached?: Array<PresentationAttachment>;
  /**
   * Redirect URI to which the user-agent should be redirected after the presentation is completed.
   * You can use the `{sessionId}` placeholder in the URI, which will be replaced with the actual session ID.
   */
  redirectUri?: string;
  /**
   * Optional ID of the access certificate to use for signing the presentation request.
   * If not provided, the default access certificate for the tenant will be used.
   *
   * Note: This is intentionally NOT a TypeORM relationship because CertEntity uses
   * a composite primary key (id + tenantId), and SQLite cannot create foreign keys
   * that reference only part of a composite primary key. The relationship is handled
   * at the application level in the service layer.
   */
  accessKeyChainId?: string;
};

export type PresentationConfigUpdateDto = {
  /**
   * Unique identifier for the VP request.
   */
  id?: string;
  /**
   * Description of the presentation configuration.
   */
  description?: string;
  /**
   * Lifetime how long the presentation request is valid after creation, in seconds.
   */
  lifeTime?: number;
  /**
   * The DCQL query to be used for the VP request.
   */
  dcql_query?: Dcql;
  transaction_data?: Array<TransactionData>;
  /**
   * The registration certificate request containing the necessary details.
   */
  registrationCert?: RegistrationCertificateRequest;
  /**
   * Optional webhook URL to receive the response.
   */
  webhook?: WebhookConfig;
  /**
   * Attestation that should be attached
   */
  attached?: Array<PresentationAttachment>;
  /**
   * Redirect URI to which the user-agent should be redirected after the presentation is completed.
   * You can use the `{sessionId}` placeholder in the URI, which will be replaced with the actual session ID.
   */
  redirectUri?: string;
  /**
   * Optional ID of the access certificate to use for signing the presentation request.
   * If not provided, the default access certificate for the tenant will be used.
   *
   * Note: This is intentionally NOT a TypeORM relationship because CertEntity uses
   * a composite primary key (id + tenantId), and SQLite cannot create foreign keys
   * that reference only part of a composite primary key. The relationship is handled
   * at the application level in the service layer.
   */
  accessKeyChainId?: string;
};

export type DeferredCredentialRequestDto = {
  /**
   * The transaction identifier previously returned by the Credential Endpoint
   */
  transaction_id: string;
};

export type NotificationRequestDto = {
  notification_id: string;
  event: {
    [key: string]: unknown;
  };
};

export type ParResponseDto = {
  /**
   * The request URI for the Pushed Authorization Request.
   */
  request_uri: string;
  /**
   * The expiration time for the request URI in seconds.
   */
  expires_in: number;
};

export type InteractiveAuthorizationRequestDto = {
  /**
   * Response type (for initial request)
   */
  response_type?: string;
  /**
   * Client identifier (for initial request)
   */
  client_id?: string;
  /**
   * Comma-separated list of supported interaction types (for initial request)
   */
  interaction_types_supported?: string;
  /**
   * Redirect URI (for initial request)
   */
  redirect_uri?: string;
  /**
   * OAuth scope
   */
  scope?: string;
  /**
   * PKCE code challenge
   */
  code_challenge?: string;
  /**
   * PKCE code challenge method
   */
  code_challenge_method?: string;
  /**
   * Authorization details
   */
  authorization_details?: {
    [key: string]: unknown;
  };
  /**
   * State parameter
   */
  state?: string;
  /**
   * Issuer state from credential offer
   */
  issuer_state?: string;
  /**
   * Auth session identifier (for follow-up request)
   */
  auth_session?: string;
  /**
   * OpenID4VP response (for follow-up request)
   */
  openid4vp_response?: string;
  /**
   * PKCE code verifier (for follow-up request)
   */
  code_verifier?: string;
  /**
   * JAR request JWT (by value)
   */
  request?: string;
  /**
   * JAR request URI (by reference)
   */
  request_uri?: string;
};

export type InteractiveAuthorizationCodeResponseDto = {
  /**
   * Response status
   */
  status: string;
  /**
   * Authorization code
   */
  code: string;
};

export type InteractiveAuthorizationErrorResponseDto = {
  /**
   * OAuth error code
   */
  error: string;
  /**
   * Human-readable error description
   */
  error_description?: string;
};

export type ChainedAsParRequestDto = {
  /**
   * OAuth response type (must be 'code')
   */
  response_type: string;
  /**
   * Client identifier (wallet identifier)
   */
  client_id: string;
  /**
   * URI to redirect the wallet after authorization
   */
  redirect_uri: string;
  /**
   * PKCE code challenge
   */
  code_challenge?: string;
  /**
   * PKCE code challenge method (e.g., S256)
   */
  code_challenge_method?: string;
  /**
   * State parameter (returned in redirect)
   */
  state?: string;
  /**
   * Scope requested
   */
  scope?: string;
  /**
   * Issuer state from credential offer
   */
  issuer_state?: string;
  /**
   * Authorization details (JSON array)
   */
  authorization_details?: Array<{
    [key: string]: unknown;
  }>;
};

export type ChainedAsParResponseDto = {
  /**
   * The request URI to use at the authorization endpoint
   */
  request_uri: string;
  /**
   * The lifetime of the request URI in seconds
   */
  expires_in: number;
};

export type ChainedAsErrorResponseDto = {
  /**
   * Error code
   */
  error: string;
  /**
   * Human-readable error description
   */
  error_description?: string;
};

export type ChainedAsTokenRequestDto = {
  /**
   * Grant type (must be 'authorization_code')
   */
  grant_type: string;
  /**
   * Authorization code received in the callback
   */
  code: string;
  /**
   * Client identifier
   */
  client_id?: string;
  /**
   * Redirect URI (must match the one used in PAR)
   */
  redirect_uri?: string;
  /**
   * PKCE code verifier
   */
  code_verifier?: string;
};

export type ChainedAsTokenResponseDto = {
  /**
   * The access token
   */
  access_token: string;
  /**
   * Token type (Bearer or DPoP)
   */
  token_type: string;
  /**
   * Token lifetime in seconds
   */
  expires_in: number;
  /**
   * Scope granted
   */
  scope?: string;
  /**
   * Authorized credential configurations
   */
  authorization_details?: Array<{
    [key: string]: unknown;
  }>;
  /**
   * C_NONCE for credential request
   */
  c_nonce?: string;
  /**
   * C_NONCE lifetime in seconds
   */
  c_nonce_expires_in?: number;
};

export type OfferResponse = {
  uri: string;
  /**
   * URI for cross-device flows (no redirect after completion)
   */
  crossDeviceUri?: string;
  session: string;
};

export type CompleteDeferredDto = {
  /**
   * Claims to include in the credential. The structure should match the credential configuration's expected claims.
   */
  claims: {
    [key: string]: unknown;
  };
};

export type DeferredOperationResponse = {
  /**
   * The transaction ID
   */
  transactionId: string;
  /**
   * The new status of the transaction
   */
  status: "pending" | "ready" | "retrieved" | "expired" | "failed";
  /**
   * Optional message
   */
  message?: string;
};

export type FailDeferredDto = {
  /**
   * Optional error message explaining why the issuance failed
   */
  error?: string;
};

export type EcPublic = {
  /**
   * The key type, which is always 'EC' for Elliptic Curve keys.
   */
  kty: string;
  /**
   * The algorithm intended for use with the key, such as 'ES256'.
   */
  crv: string;
  /**
   * The x coordinate of the EC public key.
   */
  x: string;
  /**
   * The y coordinate of the EC public key.
   */
  y: string;
};

export type JwksResponseDto = {
  /**
   * An array of EC public keys in JWK format.
   */
  keys: Array<EcPublic>;
};

export type AuthorizationResponse = {
  /**
   * The response string containing the authorization details (JWE-encrypted VP token).
   * Required for success responses, absent for error responses.
   */
  response?: string;
  /**
   * When set to true, the authorization response will be sent to the client.
   */
  sendResponse?: boolean;
  error?: string;
  /**
   * Human-readable description of the error.
   */
  error_description?: string;
  /**
   * URI with additional information about the error.
   */
  error_uri?: string;
  /**
   * State value from the authorization request (for correlation).
   */
  state?: string;
};

export type RegistrarConfigResponseDto = {
  /**
   * The base URL of the registrar API
   */
  registrarUrl: string;
  /**
   * The OIDC issuer URL for authentication (e.g., Keycloak realm URL)
   */
  oidcUrl: string;
  /**
   * The OIDC client ID for the registrar
   */
  clientId: string;
  /**
   * The OIDC client secret (optional, for confidential clients)
   */
  clientSecret?: string;
  /**
   * The username for OIDC login
   */
  username: string;
  /**
   * Indicates whether a password is configured (actual password is never returned)
   */
  hasPassword: boolean;
};

export type CreateRegistrarConfigDto = {
  /**
   * The base URL of the registrar API
   */
  registrarUrl: string;
  /**
   * The OIDC issuer URL for authentication (e.g., Keycloak realm URL)
   */
  oidcUrl: string;
  /**
   * The OIDC client ID for the registrar
   */
  clientId: string;
  /**
   * The OIDC client secret (optional, for confidential clients)
   */
  clientSecret?: string;
  /**
   * The username for OIDC login
   */
  username: string;
  /**
   * The password for OIDC login (stored in plaintext)
   */
  password: string;
};

export type UpdateRegistrarConfigDto = {
  /**
   * The base URL of the registrar API
   */
  registrarUrl?: string;
  /**
   * The OIDC issuer URL for authentication (e.g., Keycloak realm URL)
   */
  oidcUrl?: string;
  /**
   * The OIDC client ID for the registrar
   */
  clientId?: string;
  /**
   * The OIDC client secret (optional, for confidential clients)
   */
  clientSecret?: string;
  /**
   * The username for OIDC login
   */
  username?: string;
  /**
   * The password for OIDC login (stored in plaintext)
   */
  password?: string;
};

export type CreateAccessCertificateDto = {
  /**
   * The ID of the key to create an access certificate for
   */
  keyId: string;
};

export type TrustListEntityInfo = {
  name: string;
  lang?: string;
  uri?: string;
  country?: string;
  locality?: string;
  postalCode?: string;
  streetAddress?: string;
  contactUri?: string;
};

export type InternalTrustListEntity = {
  type: "internal";
  issuerKeyChainId: string;
  revocationKeyChainId: string;
  info: TrustListEntityInfo;
};

export type ExternalTrustListEntity = {
  type: "external";
  issuerCertPem: string;
  revocationCertPem: string;
  info: TrustListEntityInfo;
};

export type TrustListCreateDto = {
  entities: Array<
    | ({
        type: "internal";
      } & InternalTrustListEntity)
    | ({
        type: "external";
      } & ExternalTrustListEntity)
  >;
  id?: string;
  description?: string;
  keyChainId?: string;
  /**
   * The full trust list JSON (generated LoTE structure)
   */
  data?: {
    [key: string]: unknown;
  };
};

export type TrustList = {
  /**
   * Unique identifier for the trust list
   */
  id: string;
  description?: string;
  /**
   * The tenant ID for which the VP request is made.
   */
  tenantId: string;
  /**
   * The tenant that owns this object.
   */
  tenant: TenantEntity;
  keyChainId: string;
  keyChain: KeyChainEntity;
  /**
   * The full trust list JSON (generated LoTE structure)
   */
  data?: {
    [key: string]: unknown;
  };
  /**
   * The original entity configuration used to create this trust list.
   * Stored for round-tripping when editing.
   */
  entityConfig?: Array<{
    [key: string]: unknown;
  }>;
  /**
   * The sequence number for versioning (incremented on updates)
   */
  sequenceNumber: number;
  /**
   * The signed JWT representation of this trust list
   */
  jwt: string;
  createdAt: string;
  updatedAt: string;
};

export type TrustListVersion = {
  id: string;
  trustListId: string;
  trustList: TrustList;
  tenantId: string;
  /**
   * The sequence number at the time this version was created
   */
  sequenceNumber: number;
  /**
   * The full trust list JSON at this version
   */
  data: {
    [key: string]: unknown;
  };
  /**
   * The entity configuration at this version
   */
  entityConfig?: {
    [key: string]: unknown;
  };
  /**
   * The signed JWT at this version
   */
  jwt: string;
  createdAt: string;
};

export type KmsProviderCapabilitiesDto = {
  /**
   * Whether the provider supports importing existing keys.
   */
  canImport: boolean;
  /**
   * Whether the provider supports generating new keys.
   */
  canCreate: boolean;
  /**
   * Whether the provider supports deleting keys.
   */
  canDelete: boolean;
};

export type KmsProviderInfoDto = {
  /**
   * Unique provider ID (matches the id in kms.json).
   */
  name: string;
  /**
   * Type of the KMS provider (db, vault, aws-kms).
   */
  type: string;
  /**
   * Human-readable description of this provider instance.
   */
  description?: string;
  /**
   * Capabilities of this provider.
   */
  capabilities: KmsProviderCapabilitiesDto;
};

export type KmsProvidersResponseDto = {
  /**
   * Detailed info for each registered KMS provider.
   */
  providers: Array<KmsProviderInfoDto>;
  /**
   * The default KMS provider name.
   */
  default: string;
};

export type CertificateInfoDto = {
  /**
   * Certificate in PEM format.
   */
  pem: string;
  /**
   * Certificate subject (CN).
   */
  subject?: string;
  /**
   * Certificate issuer (CN).
   */
  issuer?: string;
  /**
   * Certificate not before date.
   */
  notBefore?: string;
  /**
   * Certificate not after date.
   */
  notAfter?: string;
  /**
   * Serial number.
   */
  serialNumber?: string;
};

export type PublicKeyInfoDto = {
  /**
   * Key type (e.g., EC).
   */
  kty: string;
  /**
   * Key algorithm (e.g., ES256).
   */
  alg?: string;
  /**
   * Key ID.
   */
  kid?: string;
  /**
   * Curve (for EC keys).
   */
  crv?: string;
};

export type RotationPolicyResponseDto = {
  /**
   * Whether automatic key rotation is enabled.
   */
  enabled: boolean;
  /**
   * Rotation interval in days.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days.
   */
  certValidityDays?: number;
  /**
   * Next scheduled rotation date.
   */
  nextRotationAt?: string;
};

export type KeyChainResponseDto = {
  /**
   * Unique identifier for the key chain.
   */
  id: string;
  /**
   * Usage type of the key chain.
   */
  usageType: "access" | "attestation" | "trustList" | "statusList" | "encrypt";
  /**
   * Type of key chain (standalone or internalChain).
   */
  type: "standalone" | "internalChain";
  /**
   * Human-readable description.
   */
  description?: string;
  /**
   * KMS provider used for this key chain.
   */
  kmsProvider: string;
  /**
   * Root CA certificate (only for internalChain type).
   */
  rootCertificate?: CertificateInfoDto;
  /**
   * Active signing key's public key info.
   */
  activePublicKey: PublicKeyInfoDto;
  /**
   * Active signing key's certificate. Not present for encryption keys.
   */
  activeCertificate?: CertificateInfoDto;
  /**
   * Previous signing key's public key info (if in grace period).
   */
  previousPublicKey?: PublicKeyInfoDto;
  /**
   * Previous signing key's certificate (if in grace period).
   */
  previousCertificate?: CertificateInfoDto;
  /**
   * Previous key expiry date.
   */
  previousKeyExpiry?: string;
  /**
   * Rotation policy configuration.
   */
  rotationPolicy: RotationPolicyResponseDto;
  /**
   * Timestamp when the key chain was created.
   */
  createdAt: string;
  /**
   * Timestamp when the key chain was last updated.
   */
  updatedAt: string;
};

export type ExportEcJwk = {
  /**
   * Key type
   */
  kty: string;
  /**
   * Curve
   */
  crv: string;
  /**
   * X coordinate (base64url)
   */
  x: string;
  /**
   * Y coordinate (base64url)
   */
  y: string;
  /**
   * Private key (base64url)
   */
  d: string;
  /**
   * Algorithm
   */
  alg?: string;
  /**
   * Key ID
   */
  kid?: string;
};

export type ExportRotationPolicyDto = {
  /**
   * Whether rotation is enabled.
   */
  enabled: boolean;
  /**
   * Rotation interval in days.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days.
   */
  certValidityDays?: number;
};

export type KeyChainExportDto = {
  /**
   * Key chain ID.
   */
  id: string;
  /**
   * Human-readable description.
   */
  description?: string;
  /**
   * Usage type for this key chain.
   */
  usageType: "access" | "attestation" | "trustList" | "statusList" | "encrypt";
  /**
   * The private key in JWK format (EC).
   */
  key: ExportEcJwk;
  /**
   * Certificate chain in PEM format (leaf first, then intermediates/CA).
   */
  crt?: Array<string>;
  /**
   * KMS provider name.
   */
  kmsProvider?: string;
  /**
   * Rotation policy.
   */
  rotationPolicy?: ExportRotationPolicyDto;
};

export type RotationPolicyCreateDto = {
  /**
   * Whether automatic key rotation is enabled.
   */
  enabled: boolean;
  /**
   * Rotation interval in days. Required when enabled is true.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days. Defaults to rotation interval + 30 days grace period.
   */
  certValidityDays?: number;
};

export type KeyChainCreateDto = {
  /**
   * Usage type determines the purpose of this key chain (access, attestation, etc.).
   */
  usageType: "access" | "attestation" | "trustList" | "statusList" | "encrypt";
  /**
   * Type of key chain to create.
   */
  type: "standalone" | "internalChain";
  /**
   * Human-readable description for the key chain.
   */
  description?: string;
  /**
   * KMS provider to use (defaults to the configured default provider).
   */
  kmsProvider?: string;
  /**
   * Rotation policy configuration. Only applicable for the signing key (root CA never rotates).
   */
  rotationPolicy?: RotationPolicyCreateDto;
};

export type EcJwk = {
  kty: string;
  x: string;
  y: string;
  crv: string;
  d: string;
  alg?: string;
  kid?: string;
};

export type RotationPolicyImportDto = {
  /**
   * Whether rotation is enabled. When true, the imported key becomes a root CA.
   */
  enabled: boolean;
  /**
   * Rotation interval in days.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days.
   */
  certValidityDays?: number;
};

export type KeyChainImportDto = {
  /**
   * ID for the key chain. If not provided, a new UUID will be generated.
   */
  id?: string;
  /**
   * The private key in JWK format.
   */
  key: EcJwk;
  /**
   * Human-readable description.
   */
  description?: string;
  /**
   * Usage type for this key chain.
   */
  usageType: "access" | "attestation" | "trustList" | "statusList" | "encrypt";
  /**
   * Certificate chain in PEM format (leaf first, then intermediates/CA).
   */
  crt?: Array<string>;
  /**
   * KMS provider to use. Defaults to 'db'.
   */
  kmsProvider?: string;
  /**
   * Rotation policy. When enabled, the imported key becomes a root CA and a new leaf key is generated.
   */
  rotationPolicy?: RotationPolicyImportDto;
};

export type RotationPolicyUpdateDto = {
  /**
   * Whether automatic key rotation is enabled.
   */
  enabled?: boolean;
  /**
   * Rotation interval in days.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days.
   */
  certValidityDays?: number;
};

export type KeyChainUpdateDto = {
  /**
   * Human-readable description for the key chain.
   */
  description?: string;
  /**
   * Rotation policy configuration.
   */
  rotationPolicy?: RotationPolicyUpdateDto;
  /**
   * Active certificate chain in PEM format. Used for external certificate updates.
   */
  activeCertificate?: string;
};

export type PresentationRequest = {
  /**
   * The type of response expected from the presentation request.
   */
  response_type: "uri" | "dc-api";
  /**
   * Identifier of the presentation configuration
   */
  requestId: string;
  /**
   * Webhook configuration to receive the response.
   * If not provided, the configured webhook from the configuration will be used.
   */
  webhook?: WebhookConfig;
  /**
   * Optional redirect URI to which the user-agent should be redirected after the presentation is completed.
   * You can use the `{sessionId}` placeholder in the URI, which will be replaced with the actual session ID.
   */
  redirectUri?: string;
  /**
   * Optional transaction data to include in the OID4VP request.
   * If provided, this will override the transaction_data from the presentation configuration.
   */
  transaction_data?: Array<TransactionData>;
};

export type FileUploadDto = {
  file: Blob | File;
};

export type AppControllerGetVersionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/version";
};

export type AppControllerGetVersionResponses = {
  /**
   * Service version info
   */
  200: unknown;
};

export type TenantControllerGetTenantsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/tenant";
};

export type TenantControllerGetTenantsResponses = {
  200: Array<TenantEntity>;
};

export type TenantControllerGetTenantsResponse =
  TenantControllerGetTenantsResponses[keyof TenantControllerGetTenantsResponses];

export type TenantControllerInitTenantData = {
  body: CreateTenantDto;
  path?: never;
  query?: never;
  url: "/api/tenant";
};

export type TenantControllerInitTenantResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type TenantControllerInitTenantResponse =
  TenantControllerInitTenantResponses[keyof TenantControllerInitTenantResponses];

export type TenantControllerDeleteTenantData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tenant/{id}";
};

export type TenantControllerDeleteTenantResponses = {
  200: unknown;
};

export type TenantControllerGetTenantData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tenant/{id}";
};

export type TenantControllerGetTenantResponses = {
  200: TenantEntity;
};

export type TenantControllerGetTenantResponse =
  TenantControllerGetTenantResponses[keyof TenantControllerGetTenantResponses];

export type TenantControllerUpdateTenantData = {
  body: UpdateTenantDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tenant/{id}";
};

export type TenantControllerUpdateTenantResponses = {
  200: TenantEntity;
};

export type TenantControllerUpdateTenantResponse =
  TenantControllerUpdateTenantResponses[keyof TenantControllerUpdateTenantResponses];

export type ClientControllerGetClientsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/client";
};

export type ClientControllerGetClientsResponses = {
  200: Array<ClientEntity>;
};

export type ClientControllerGetClientsResponse =
  ClientControllerGetClientsResponses[keyof ClientControllerGetClientsResponses];

export type ClientControllerCreateClientData = {
  body: CreateClientDto;
  path?: never;
  query?: never;
  url: "/api/client";
};

export type ClientControllerCreateClientResponses = {
  201: ClientEntity;
};

export type ClientControllerCreateClientResponse =
  ClientControllerCreateClientResponses[keyof ClientControllerCreateClientResponses];

export type ClientControllerDeleteClientData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}";
};

export type ClientControllerDeleteClientResponses = {
  200: unknown;
};

export type ClientControllerGetClientData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}";
};

export type ClientControllerGetClientResponses = {
  200: ClientEntity;
};

export type ClientControllerGetClientResponse =
  ClientControllerGetClientResponses[keyof ClientControllerGetClientResponses];

export type ClientControllerUpdateClientData = {
  body: UpdateClientDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}";
};

export type ClientControllerUpdateClientResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type ClientControllerUpdateClientResponse =
  ClientControllerUpdateClientResponses[keyof ClientControllerUpdateClientResponses];

export type ClientControllerGetClientSecretData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}/secret";
};

export type ClientControllerGetClientSecretResponses = {
  200: ClientSecretResponseDto;
};

export type ClientControllerGetClientSecretResponse =
  ClientControllerGetClientSecretResponses[keyof ClientControllerGetClientSecretResponses];

export type ClientControllerRotateClientSecretData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}/rotate-secret";
};

export type ClientControllerRotateClientSecretResponses = {
  201: ClientSecretResponseDto;
};

export type ClientControllerRotateClientSecretResponse =
  ClientControllerRotateClientSecretResponses[keyof ClientControllerRotateClientSecretResponses];

export type StatusListConfigControllerResetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/status-list-config";
};

export type StatusListConfigControllerResetConfigResponses = {
  /**
   * Configuration reset successfully
   */
  204: void;
};

export type StatusListConfigControllerResetConfigResponse =
  StatusListConfigControllerResetConfigResponses[keyof StatusListConfigControllerResetConfigResponses];

export type StatusListConfigControllerGetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/status-list-config";
};

export type StatusListConfigControllerGetConfigResponses = {
  /**
   * The status list configuration
   */
  200: StatusListConfig;
};

export type StatusListConfigControllerGetConfigResponse =
  StatusListConfigControllerGetConfigResponses[keyof StatusListConfigControllerGetConfigResponses];

export type StatusListConfigControllerUpdateConfigData = {
  body: UpdateStatusListConfigDto;
  path?: never;
  query?: never;
  url: "/api/status-list-config";
};

export type StatusListConfigControllerUpdateConfigResponses = {
  /**
   * The updated status list configuration
   */
  200: StatusListConfig;
};

export type StatusListConfigControllerUpdateConfigResponse =
  StatusListConfigControllerUpdateConfigResponses[keyof StatusListConfigControllerUpdateConfigResponses];

export type StatusListManagementControllerGetListsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/status-lists";
};

export type StatusListManagementControllerGetListsResponses = {
  /**
   * List of status lists
   */
  200: Array<StatusListResponseDto>;
};

export type StatusListManagementControllerGetListsResponse =
  StatusListManagementControllerGetListsResponses[keyof StatusListManagementControllerGetListsResponses];

export type StatusListManagementControllerCreateListData = {
  body: CreateStatusListDto;
  path?: never;
  query?: never;
  url: "/api/status-lists";
};

export type StatusListManagementControllerCreateListResponses = {
  /**
   * The created status list
   */
  201: StatusListResponseDto;
};

export type StatusListManagementControllerCreateListResponse =
  StatusListManagementControllerCreateListResponses[keyof StatusListManagementControllerCreateListResponses];

export type StatusListManagementControllerDeleteListData = {
  body?: never;
  path: {
    /**
     * The status list ID
     */
    listId: string;
  };
  query?: never;
  url: "/api/status-lists/{listId}";
};

export type StatusListManagementControllerDeleteListResponses = {
  /**
   * Status list deleted successfully
   */
  204: void;
};

export type StatusListManagementControllerDeleteListResponse =
  StatusListManagementControllerDeleteListResponses[keyof StatusListManagementControllerDeleteListResponses];

export type StatusListManagementControllerGetListData = {
  body?: never;
  path: {
    /**
     * The status list ID
     */
    listId: string;
  };
  query?: never;
  url: "/api/status-lists/{listId}";
};

export type StatusListManagementControllerGetListResponses = {
  /**
   * The status list
   */
  200: StatusListResponseDto;
};

export type StatusListManagementControllerGetListResponse =
  StatusListManagementControllerGetListResponses[keyof StatusListManagementControllerGetListResponses];

export type StatusListManagementControllerUpdateListData = {
  body: UpdateStatusListDto;
  path: {
    /**
     * The status list ID
     */
    listId: string;
  };
  query?: never;
  url: "/api/status-lists/{listId}";
};

export type StatusListManagementControllerUpdateListResponses = {
  /**
   * The updated status list
   */
  200: StatusListResponseDto;
};

export type StatusListManagementControllerUpdateListResponse =
  StatusListManagementControllerUpdateListResponses[keyof StatusListManagementControllerUpdateListResponses];

export type SessionControllerGetAllSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/session";
};

export type SessionControllerGetAllSessionsResponses = {
  200: Array<Session>;
};

export type SessionControllerGetAllSessionsResponse =
  SessionControllerGetAllSessionsResponses[keyof SessionControllerGetAllSessionsResponses];

export type SessionControllerDeleteSessionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/session/{id}";
};

export type SessionControllerDeleteSessionResponses = {
  200: unknown;
};

export type SessionControllerGetSessionData = {
  body?: never;
  path: {
    /**
     * The session ID
     */
    id: string;
  };
  query?: never;
  url: "/api/session/{id}";
};

export type SessionControllerGetSessionResponses = {
  200: Session;
};

export type SessionControllerGetSessionResponse =
  SessionControllerGetSessionResponses[keyof SessionControllerGetSessionResponses];

export type SessionControllerGetSessionLogsData = {
  body?: never;
  path: {
    /**
     * The session ID
     */
    id: string;
  };
  query?: never;
  url: "/api/session/{id}/logs";
};

export type SessionControllerGetSessionLogsResponses = {
  200: Array<SessionLogEntryResponseDto>;
};

export type SessionControllerGetSessionLogsResponse =
  SessionControllerGetSessionLogsResponses[keyof SessionControllerGetSessionLogsResponses];

export type SessionControllerRevokeAllData = {
  body: StatusUpdateDto;
  path?: never;
  query?: never;
  url: "/api/session/revoke";
};

export type SessionControllerRevokeAllResponses = {
  201: unknown;
};

export type SessionConfigControllerResetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/session-config";
};

export type SessionConfigControllerResetConfigResponses = {
  /**
   * Configuration reset successfully
   */
  200: unknown;
};

export type SessionConfigControllerGetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/session-config";
};

export type SessionConfigControllerGetConfigResponses = {
  /**
   * The session storage configuration
   */
  200: SessionStorageConfig;
};

export type SessionConfigControllerGetConfigResponse =
  SessionConfigControllerGetConfigResponses[keyof SessionConfigControllerGetConfigResponses];

export type SessionConfigControllerUpdateConfigData = {
  body: UpdateSessionConfigDto;
  path?: never;
  query?: never;
  url: "/api/session-config";
};

export type SessionConfigControllerUpdateConfigResponses = {
  /**
   * The updated session storage configuration
   */
  200: SessionStorageConfig;
};

export type SessionConfigControllerUpdateConfigResponse =
  SessionConfigControllerUpdateConfigResponses[keyof SessionConfigControllerUpdateConfigResponses];

export type SessionEventsControllerSubscribeToSessionEventsData = {
  body?: never;
  path: {
    /**
     * Session ID to subscribe to
     */
    id: string;
  };
  query: {
    /**
     * JWT access token for authentication
     */
    token: string;
  };
  url: "/api/session/{id}/events";
};

export type SessionEventsControllerSubscribeToSessionEventsResponses = {
  200: unknown;
};

export type IssuanceConfigControllerGetIssuanceConfigurationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/issuer/config";
};

export type IssuanceConfigControllerGetIssuanceConfigurationsResponses = {
  200: IssuanceConfig;
};

export type IssuanceConfigControllerGetIssuanceConfigurationsResponse =
  IssuanceConfigControllerGetIssuanceConfigurationsResponses[keyof IssuanceConfigControllerGetIssuanceConfigurationsResponses];

export type IssuanceConfigControllerStoreIssuanceConfigurationData = {
  body: IssuanceDto;
  path?: never;
  query?: never;
  url: "/api/issuer/config";
};

export type IssuanceConfigControllerStoreIssuanceConfigurationResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type IssuanceConfigControllerStoreIssuanceConfigurationResponse =
  IssuanceConfigControllerStoreIssuanceConfigurationResponses[keyof IssuanceConfigControllerStoreIssuanceConfigurationResponses];

export type CredentialConfigControllerGetConfigsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/issuer/credentials";
};

export type CredentialConfigControllerGetConfigsResponses = {
  200: Array<CredentialConfig>;
};

export type CredentialConfigControllerGetConfigsResponse =
  CredentialConfigControllerGetConfigsResponses[keyof CredentialConfigControllerGetConfigsResponses];

export type CredentialConfigControllerStoreCredentialConfigurationData = {
  body: CredentialConfigCreate;
  path?: never;
  query?: never;
  url: "/api/issuer/credentials";
};

export type CredentialConfigControllerStoreCredentialConfigurationResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type CredentialConfigControllerStoreCredentialConfigurationResponse =
  CredentialConfigControllerStoreCredentialConfigurationResponses[keyof CredentialConfigControllerStoreCredentialConfigurationResponses];

export type CredentialConfigControllerDeleteIssuanceConfigurationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/credentials/{id}";
};

export type CredentialConfigControllerDeleteIssuanceConfigurationResponses = {
  200: unknown;
};

export type CredentialConfigControllerGetConfigByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/credentials/{id}";
};

export type CredentialConfigControllerGetConfigByIdResponses = {
  200: CredentialConfig;
};

export type CredentialConfigControllerGetConfigByIdResponse =
  CredentialConfigControllerGetConfigByIdResponses[keyof CredentialConfigControllerGetConfigByIdResponses];

export type CredentialConfigControllerUpdateCredentialConfigurationData = {
  body: CredentialConfigUpdate;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/credentials/{id}";
};

export type CredentialConfigControllerUpdateCredentialConfigurationResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type CredentialConfigControllerUpdateCredentialConfigurationResponse =
  CredentialConfigControllerUpdateCredentialConfigurationResponses[keyof CredentialConfigControllerUpdateCredentialConfigurationResponses];

export type AttributeProviderControllerGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/issuer/attribute-providers";
};

export type AttributeProviderControllerGetAllResponses = {
  /**
   * List of attribute providers
   */
  200: unknown;
};

export type AttributeProviderControllerCreateData = {
  body: CreateAttributeProviderDto;
  path?: never;
  query?: never;
  url: "/api/issuer/attribute-providers";
};

export type AttributeProviderControllerCreateResponses = {
  /**
   * Attribute provider created
   */
  201: unknown;
};

export type AttributeProviderControllerDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/attribute-providers/{id}";
};

export type AttributeProviderControllerDeleteErrors = {
  /**
   * Attribute provider not found
   */
  404: unknown;
};

export type AttributeProviderControllerDeleteResponses = {
  /**
   * Attribute provider deleted
   */
  200: unknown;
};

export type AttributeProviderControllerGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/attribute-providers/{id}";
};

export type AttributeProviderControllerGetByIdErrors = {
  /**
   * Attribute provider not found
   */
  404: unknown;
};

export type AttributeProviderControllerGetByIdResponses = {
  /**
   * The attribute provider
   */
  200: unknown;
};

export type AttributeProviderControllerUpdateData = {
  body: UpdateAttributeProviderDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/attribute-providers/{id}";
};

export type AttributeProviderControllerUpdateErrors = {
  /**
   * Attribute provider not found
   */
  404: unknown;
};

export type AttributeProviderControllerUpdateResponses = {
  /**
   * Attribute provider updated
   */
  200: unknown;
};

export type WebhookEndpointControllerGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/issuer/webhook-endpoints";
};

export type WebhookEndpointControllerGetAllResponses = {
  /**
   * List of webhook endpoints
   */
  200: unknown;
};

export type WebhookEndpointControllerCreateData = {
  body: CreateWebhookEndpointDto;
  path?: never;
  query?: never;
  url: "/api/issuer/webhook-endpoints";
};

export type WebhookEndpointControllerCreateResponses = {
  /**
   * Webhook endpoint created
   */
  201: unknown;
};

export type WebhookEndpointControllerDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/webhook-endpoints/{id}";
};

export type WebhookEndpointControllerDeleteErrors = {
  /**
   * Webhook endpoint not found
   */
  404: unknown;
};

export type WebhookEndpointControllerDeleteResponses = {
  /**
   * Webhook endpoint deleted
   */
  200: unknown;
};

export type WebhookEndpointControllerGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/webhook-endpoints/{id}";
};

export type WebhookEndpointControllerGetByIdErrors = {
  /**
   * Webhook endpoint not found
   */
  404: unknown;
};

export type WebhookEndpointControllerGetByIdResponses = {
  /**
   * The webhook endpoint
   */
  200: unknown;
};

export type WebhookEndpointControllerUpdateData = {
  body: UpdateWebhookEndpointDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/webhook-endpoints/{id}";
};

export type WebhookEndpointControllerUpdateErrors = {
  /**
   * Webhook endpoint not found
   */
  404: unknown;
};

export type WebhookEndpointControllerUpdateResponses = {
  /**
   * Webhook endpoint updated
   */
  200: unknown;
};

export type PresentationManagementControllerConfigurationData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/verifier/config";
};

export type PresentationManagementControllerConfigurationResponses = {
  200: Array<PresentationConfig>;
};

export type PresentationManagementControllerConfigurationResponse =
  PresentationManagementControllerConfigurationResponses[keyof PresentationManagementControllerConfigurationResponses];

export type PresentationManagementControllerStorePresentationConfigData = {
  body: PresentationConfigCreateDto;
  path?: never;
  query?: never;
  url: "/api/verifier/config";
};

export type PresentationManagementControllerStorePresentationConfigResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type PresentationManagementControllerStorePresentationConfigResponse =
  PresentationManagementControllerStorePresentationConfigResponses[keyof PresentationManagementControllerStorePresentationConfigResponses];

export type PresentationManagementControllerDeleteConfigurationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/verifier/config/{id}";
};

export type PresentationManagementControllerDeleteConfigurationResponses = {
  200: unknown;
};

export type PresentationManagementControllerGetConfigurationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/verifier/config/{id}";
};

export type PresentationManagementControllerGetConfigurationResponses = {
  200: PresentationConfig;
};

export type PresentationManagementControllerGetConfigurationResponse =
  PresentationManagementControllerGetConfigurationResponses[keyof PresentationManagementControllerGetConfigurationResponses];

export type PresentationManagementControllerUpdateConfigurationData = {
  body: PresentationConfigUpdateDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/verifier/config/{id}";
};

export type PresentationManagementControllerUpdateConfigurationResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type PresentationManagementControllerUpdateConfigurationResponse =
  PresentationManagementControllerUpdateConfigurationResponses[keyof PresentationManagementControllerUpdateConfigurationResponses];

export type CacheControllerGetStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/cache/stats";
};

export type CacheControllerGetStatsResponses = {
  /**
   * Cache statistics
   */
  200: unknown;
};

export type CacheControllerClearAllCachesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/cache";
};

export type CacheControllerClearAllCachesResponses = {
  /**
   * All caches cleared successfully
   */
  204: void;
};

export type CacheControllerClearAllCachesResponse =
  CacheControllerClearAllCachesResponses[keyof CacheControllerClearAllCachesResponses];

export type CacheControllerClearTrustListCacheData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/cache/trust-list";
};

export type CacheControllerClearTrustListCacheResponses = {
  /**
   * Trust list cache cleared successfully
   */
  204: void;
};

export type CacheControllerClearTrustListCacheResponse =
  CacheControllerClearTrustListCacheResponses[keyof CacheControllerClearTrustListCacheResponses];

export type CacheControllerClearStatusListCacheData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/cache/status-list";
};

export type CacheControllerClearStatusListCacheResponses = {
  /**
   * Status list cache cleared successfully
   */
  204: void;
};

export type CacheControllerClearStatusListCacheResponse =
  CacheControllerClearStatusListCacheResponses[keyof CacheControllerClearStatusListCacheResponses];

export type CredentialOfferControllerGetOfferData = {
  body: OfferRequestDto;
  path?: never;
  query?: never;
  url: "/api/issuer/offer";
};

export type CredentialOfferControllerGetOfferResponses = {
  /**
   * JSON response
   */
  201: OfferResponse;
};

export type CredentialOfferControllerGetOfferResponse =
  CredentialOfferControllerGetOfferResponses[keyof CredentialOfferControllerGetOfferResponses];

export type DeferredControllerCompleteDeferredData = {
  body: CompleteDeferredDto;
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/api/issuer/deferred/{transactionId}/complete";
};

export type DeferredControllerCompleteDeferredErrors = {
  /**
   * Transaction not found
   */
  404: unknown;
};

export type DeferredControllerCompleteDeferredResponses = {
  /**
   * Transaction completed successfully
   */
  200: DeferredOperationResponse;
};

export type DeferredControllerCompleteDeferredResponse =
  DeferredControllerCompleteDeferredResponses[keyof DeferredControllerCompleteDeferredResponses];

export type DeferredControllerFailDeferredData = {
  body?: FailDeferredDto;
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/api/issuer/deferred/{transactionId}/fail";
};

export type DeferredControllerFailDeferredErrors = {
  /**
   * Transaction not found
   */
  404: unknown;
};

export type DeferredControllerFailDeferredResponses = {
  /**
   * Transaction marked as failed
   */
  200: DeferredOperationResponse;
};

export type DeferredControllerFailDeferredResponse =
  DeferredControllerFailDeferredResponses[keyof DeferredControllerFailDeferredResponses];

export type RegistrarControllerDeleteConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/registrar/config";
};

export type RegistrarControllerDeleteConfigResponses = {
  /**
   * Configuration deleted successfully
   */
  204: void;
};

export type RegistrarControllerDeleteConfigResponse =
  RegistrarControllerDeleteConfigResponses[keyof RegistrarControllerDeleteConfigResponses];

export type RegistrarControllerGetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/registrar/config";
};

export type RegistrarControllerGetConfigErrors = {
  /**
   * No registrar configuration found
   */
  404: unknown;
};

export type RegistrarControllerGetConfigResponses = {
  /**
   * The registrar configuration
   */
  200: RegistrarConfigResponseDto;
};

export type RegistrarControllerGetConfigResponse =
  RegistrarControllerGetConfigResponses[keyof RegistrarControllerGetConfigResponses];

export type RegistrarControllerUpdateConfigData = {
  body: UpdateRegistrarConfigDto;
  path?: never;
  query?: never;
  url: "/api/registrar/config";
};

export type RegistrarControllerUpdateConfigErrors = {
  /**
   * Invalid credentials
   */
  400: unknown;
  /**
   * No registrar configuration found
   */
  404: unknown;
};

export type RegistrarControllerUpdateConfigResponses = {
  /**
   * Configuration updated successfully
   */
  200: RegistrarConfigResponseDto;
};

export type RegistrarControllerUpdateConfigResponse =
  RegistrarControllerUpdateConfigResponses[keyof RegistrarControllerUpdateConfigResponses];

export type RegistrarControllerCreateConfigData = {
  body: CreateRegistrarConfigDto;
  path?: never;
  query?: never;
  url: "/api/registrar/config";
};

export type RegistrarControllerCreateConfigErrors = {
  /**
   * Invalid credentials
   */
  400: unknown;
};

export type RegistrarControllerCreateConfigResponses = {
  /**
   * Configuration created successfully
   */
  201: RegistrarConfigResponseDto;
};

export type RegistrarControllerCreateConfigResponse =
  RegistrarControllerCreateConfigResponses[keyof RegistrarControllerCreateConfigResponses];

export type RegistrarControllerCreateAccessCertificateData = {
  body: CreateAccessCertificateDto;
  path?: never;
  query?: never;
  url: "/api/registrar/access-certificate";
};

export type RegistrarControllerCreateAccessCertificateErrors = {
  /**
   * No relying party found at registrar or failed to create certificate
   */
  400: unknown;
  /**
   * No registrar configuration found or key not found
   */
  404: unknown;
};

export type RegistrarControllerCreateAccessCertificateResponses = {
  /**
   * Access certificate created successfully
   */
  201: {
    /**
     * The certificate ID at the registrar
     */
    id?: string;
    /**
     * The certificate in PEM format
     */
    crt?: string;
  };
};

export type RegistrarControllerCreateAccessCertificateResponse =
  RegistrarControllerCreateAccessCertificateResponses[keyof RegistrarControllerCreateAccessCertificateResponses];

export type TrustListControllerGetAllTrustListsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/trust-list";
};

export type TrustListControllerGetAllTrustListsResponses = {
  200: Array<TrustList>;
};

export type TrustListControllerGetAllTrustListsResponse =
  TrustListControllerGetAllTrustListsResponses[keyof TrustListControllerGetAllTrustListsResponses];

export type TrustListControllerCreateTrustListData = {
  body: TrustListCreateDto;
  path?: never;
  query?: never;
  url: "/api/trust-list";
};

export type TrustListControllerCreateTrustListResponses = {
  201: TrustList;
};

export type TrustListControllerCreateTrustListResponse =
  TrustListControllerCreateTrustListResponses[keyof TrustListControllerCreateTrustListResponses];

export type TrustListControllerDeleteTrustListData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}";
};

export type TrustListControllerDeleteTrustListResponses = {
  200: unknown;
};

export type TrustListControllerGetTrustListData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}";
};

export type TrustListControllerGetTrustListResponses = {
  200: TrustList;
};

export type TrustListControllerGetTrustListResponse =
  TrustListControllerGetTrustListResponses[keyof TrustListControllerGetTrustListResponses];

export type TrustListControllerUpdateTrustListData = {
  body: TrustListCreateDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}";
};

export type TrustListControllerUpdateTrustListResponses = {
  200: TrustList;
};

export type TrustListControllerUpdateTrustListResponse =
  TrustListControllerUpdateTrustListResponses[keyof TrustListControllerUpdateTrustListResponses];

export type TrustListControllerExportTrustListData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}/export";
};

export type TrustListControllerExportTrustListResponses = {
  200: TrustListCreateDto;
};

export type TrustListControllerExportTrustListResponse =
  TrustListControllerExportTrustListResponses[keyof TrustListControllerExportTrustListResponses];

export type TrustListControllerGetTrustListVersionsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}/versions";
};

export type TrustListControllerGetTrustListVersionsResponses = {
  200: Array<TrustListVersion>;
};

export type TrustListControllerGetTrustListVersionsResponse =
  TrustListControllerGetTrustListVersionsResponses[keyof TrustListControllerGetTrustListVersionsResponses];

export type TrustListControllerGetTrustListVersionData = {
  body?: never;
  path: {
    id: string;
    versionId: string;
  };
  query?: never;
  url: "/api/trust-list/{id}/versions/{versionId}";
};

export type TrustListControllerGetTrustListVersionResponses = {
  200: TrustListVersion;
};

export type TrustListControllerGetTrustListVersionResponse =
  TrustListControllerGetTrustListVersionResponses[keyof TrustListControllerGetTrustListVersionResponses];

export type KeyChainControllerGetProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/key-chain/providers";
};

export type KeyChainControllerGetProvidersResponses = {
  /**
   * List of available KMS providers with capabilities
   */
  200: KmsProvidersResponseDto;
};

export type KeyChainControllerGetProvidersResponse =
  KeyChainControllerGetProvidersResponses[keyof KeyChainControllerGetProvidersResponses];

export type KeyChainControllerGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/key-chain";
};

export type KeyChainControllerGetAllResponses = {
  /**
   * List of key chains
   */
  200: Array<KeyChainResponseDto>;
};

export type KeyChainControllerGetAllResponse =
  KeyChainControllerGetAllResponses[keyof KeyChainControllerGetAllResponses];

export type KeyChainControllerCreateData = {
  body: KeyChainCreateDto;
  path?: never;
  query?: never;
  url: "/api/key-chain";
};

export type KeyChainControllerCreateResponses = {
  /**
   * Key chain created successfully
   */
  201: unknown;
};

export type KeyChainControllerDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}";
};

export type KeyChainControllerDeleteErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerDeleteResponses = {
  /**
   * Key chain deleted successfully
   */
  200: unknown;
};

export type KeyChainControllerGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}";
};

export type KeyChainControllerGetByIdErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerGetByIdResponses = {
  /**
   * The key chain
   */
  200: KeyChainResponseDto;
};

export type KeyChainControllerGetByIdResponse =
  KeyChainControllerGetByIdResponses[keyof KeyChainControllerGetByIdResponses];

export type KeyChainControllerUpdateData = {
  body: KeyChainUpdateDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}";
};

export type KeyChainControllerUpdateErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerUpdateResponses = {
  /**
   * Key chain updated successfully
   */
  200: unknown;
};

export type KeyChainControllerExportData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}/export";
};

export type KeyChainControllerExportErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerExportResponses = {
  /**
   * Key chain export data
   */
  200: KeyChainExportDto;
};

export type KeyChainControllerExportResponse =
  KeyChainControllerExportResponses[keyof KeyChainControllerExportResponses];

export type KeyChainControllerImportData = {
  body: KeyChainImportDto;
  path?: never;
  query?: never;
  url: "/api/key-chain/import";
};

export type KeyChainControllerImportResponses = {
  /**
   * Key chain imported successfully
   */
  201: unknown;
};

export type KeyChainControllerRotateData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}/rotate";
};

export type KeyChainControllerRotateErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerRotateResponses = {
  /**
   * Key chain rotated successfully
   */
  200: unknown;
  201: unknown;
};

export type VerifierOfferControllerGetOfferData = {
  body: PresentationRequest;
  path?: never;
  query?: never;
  url: "/api/verifier/offer";
};

export type VerifierOfferControllerGetOfferResponses = {
  /**
   * JSON response
   */
  201: OfferResponse;
};

export type VerifierOfferControllerGetOfferResponse =
  VerifierOfferControllerGetOfferResponses[keyof VerifierOfferControllerGetOfferResponses];

export type StorageControllerUploadData = {
  body: FileUploadDto;
  path?: never;
  query?: never;
  url: "/api/storage";
};

export type StorageControllerUploadResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type StorageControllerUploadResponse =
  StorageControllerUploadResponses[keyof StorageControllerUploadResponses];
