// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type GrafanaConfigDto = {
  /**
   * Base URL of the Grafana instance
   */
  url?: string;
  /**
   * UID of the Tempo data source in Grafana
   */
  tempoUid: string;
  /**
   * UID of the Loki data source in Grafana
   */
  lokiUid: string;
};

export type FrontendConfigResponseDto = {
  /**
   * Grafana observability configuration
   */
  grafana: GrafanaConfigDto;
};

export type RoleDto = {
  /**
   * OAuth2 roles
   */
  role:
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "users:manage"
    | "tenants:manage"
    | "registrar:manage";
};

export type ClientCredentialsDto = {
  grant_type?: string;
};

export type TokenResponse = {
  [key: string]: unknown;
};

export type ImportTenantDto = {
  [key: string]: unknown;
};

export type StatusListConfig = {
  /**
   * The capacity of the status list. If not set, uses global STATUS_CAPACITY.
   */
  capacity?: number;
  /**
   * Bits per status entry: 1 (valid/revoked), 2 (with suspended), 4/8 (extended). If not set, uses global STATUS_BITS.
   */
  bits?: 1 | 2 | 4 | 8;
  /**
   * TTL in seconds for the status list JWT. If not set, uses global STATUS_TTL.
   */
  ttl?: number;
  /**
   * If true, regenerate JWT immediately on status changes. If false (default), use lazy regeneration on TTL expiry.
   */
  immediateUpdate?: boolean;
  /**
   * If true, include aggregation_uri in status list JWTs for pre-fetching support (default: true).
   */
  enableAggregation?: boolean;
};

export type SessionStorageConfig = {
  /**
   * Time-to-live for sessions in seconds. If not set, uses global SESSION_TTL.
   */
  ttlSeconds?: number;
  /**
   * Cleanup mode: 'full' deletes everything, 'anonymize' keeps metadata but removes PII.
   */
  cleanupMode?: "full" | "anonymize";
};

export type CreateTenantDto = {
  /**
   * Status list configuration for this tenant. Only affects newly created status lists.
   */
  statusListConfig?: StatusListConfig;
  /**
   * Session storage configuration. Controls TTL and cleanup behavior.
   */
  sessionConfig?: SessionStorageConfig;
};

export type UpdateTenantDto = {
  /**
   * Status list configuration for this tenant. Only affects newly created status lists.
   */
  statusListConfig?: StatusListConfig;
  /**
   * Session storage configuration. Controls TTL and cleanup behavior.
   */
  sessionConfig?: SessionStorageConfig;
};

export type UpdateClientDto = {
  /**
   * List of presentation config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedPresentationConfigs?: Array<string>;
  /**
   * List of issuance config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedIssuanceConfigs?: Array<string>;
};

export type CreateClientDto = {
  /**
   * List of presentation config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedPresentationConfigs?: Array<string>;
  /**
   * List of issuance config IDs this client can use. If empty/null, all configs are allowed.
   */
  allowedIssuanceConfigs?: Array<string>;
};

export type StatusListImportDto = {
  /**
   * Unique identifier for the status list
   */
  id: string;
  /**
   * Credential configuration ID to bind this list exclusively to. Leave empty for a shared list.
   */
  credentialConfigurationId?: {
    [key: string]: unknown;
  };
  /**
   * Key chain ID to use for signing. Leave empty to use the tenant's default StatusList key chain.
   */
  keyChainId?: string;
  /**
   * Capacity of the status list. If not provided, uses tenant or global defaults.
   */
  capacity?: number;
  /**
   * Bits per status value. If not provided, uses tenant or global defaults.
   */
  bits?: 1 | 2 | 4 | 8;
};

export type StatusListAggregationDto = {
  /**
   * Array of status list token URIs
   */
  status_lists: Array<string>;
};

export type UpdateStatusListConfigDto = {
  /**
   * The capacity of the status list. Set to null to reset to global default.
   */
  capacity?: {
    [key: string]: unknown;
  };
  /**
   * Bits per status entry. Set to null to reset to global default.
   */
  bits?: 1 | 2 | 4 | 8;
  /**
   * TTL in seconds for the status list JWT. Set to null to reset to global default.
   */
  ttl?: {
    [key: string]: unknown;
  };
  /**
   * If true, regenerate JWT on every status change. Set to null to reset to default (false).
   */
  immediateUpdate?: {
    [key: string]: unknown;
  };
  /**
   * If true, include aggregation_uri in status list JWTs for pre-fetching support. Set to null to reset to default (true).
   */
  enableAggregation?: {
    [key: string]: unknown;
  };
};

export type StatusListResponseDto = {
  /**
   * Unique identifier for the status list
   */
  id: string;
  /**
   * The tenant ID
   */
  tenantId: string;
  /**
   * Credential configuration ID this list is bound to. Null means shared.
   */
  credentialConfigurationId?: {
    [key: string]: unknown;
  };
  /**
   * Key chain ID used for signing. Null means using the tenant's default.
   */
  keyChainId?: {
    [key: string]: unknown;
  };
  /**
   * Bits per status value
   */
  bits: 1 | 2 | 4 | 8;
  /**
   * Total capacity of the status list
   */
  capacity: number;
  /**
   * Number of entries in use
   */
  usedEntries: number;
  /**
   * Number of available entries
   */
  availableEntries: number;
  /**
   * The public URI for this status list
   */
  uri: string;
  /**
   * Creation timestamp
   */
  createdAt: string;
  /**
   * JWT expiration timestamp. Null if JWT has not been generated yet.
   */
  expiresAt?: {
    [key: string]: unknown;
  };
};

export type CreateStatusListDto = {
  /**
   * Credential configuration ID to bind this list exclusively to. Leave empty for a shared list.
   */
  credentialConfigurationId?: string;
  /**
   * Key chain ID to use for signing. Leave empty to use the tenant's default StatusList key chain.
   */
  keyChainId?: string;
  /**
   * Bits per status value. More bits allow more status states. Defaults to tenant configuration.
   */
  bits?: 1 | 2 | 4 | 8;
  /**
   * Maximum number of credential status entries. Defaults to tenant configuration.
   */
  capacity?: number;
};

export type UpdateStatusListDto = {
  /**
   * Credential configuration ID to bind this list exclusively to. Set to null to make this a shared list.
   */
  credentialConfigurationId?: {
    [key: string]: unknown;
  };
  /**
   * Key chain ID to use for signing. Set to null to use the tenant's default StatusList key chain.
   */
  keyChainId?: {
    [key: string]: unknown;
  };
};

export type SessionLogEntryResponseDto = {
  /**
   * Log entry ID
   */
  id: string;
  /**
   * Session ID
   */
  sessionId: string;
  /**
   * Timestamp of the log entry
   */
  timestamp: string;
  /**
   * Log level
   */
  level: "info" | "warn" | "error";
  /**
   * Flow stage
   */
  stage?: string;
  /**
   * Log message
   */
  message: string;
  /**
   * Additional structured detail
   */
  detail?: {
    [key: string]: unknown;
  };
};

export type StatusUpdateDto = {
  [key: string]: unknown;
};

export type UpdateSessionConfigDto = {
  /**
   * Time-to-live for sessions in seconds. Set to null to use global default.
   */
  ttlSeconds?: {
    [key: string]: unknown;
  };
  /**
   * Cleanup mode: 'full' deletes everything, 'anonymize' keeps metadata but removes PII.
   */
  cleanupMode?: "full" | "anonymize";
};

export type ManagedUserDto = {
  id: string;
  username: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  enabled: boolean;
  roles: Array<
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "users:manage"
    | "tenants:manage"
    | "registrar:manage"
  >;
  tenantId?: string;
};

export type CreateUserDto = {
  username: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  roles: Array<
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "users:manage"
    | "tenants:manage"
    | "registrar:manage"
  >;
  password: string;
  enabled?: boolean;
};

export type UpdateUserDto = {
  username?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  roles?: Array<
    | "presentation:manage"
    | "presentation:request"
    | "issuance:manage"
    | "issuance:offer"
    | "clients:manage"
    | "users:manage"
    | "tenants:manage"
    | "registrar:manage"
  >;
  password?: string;
  enabled?: boolean;
};

export type UpstreamOidcConfig = {
  /**
   * The OIDC issuer URL of the upstream provider
   */
  issuer: string;
  /**
   * The client ID registered with the upstream provider
   */
  clientId: string;
  /**
   * The client secret for confidential clients
   */
  clientSecret?: string;
  /**
   * Scopes to request from the upstream provider
   */
  scopes?: Array<string>;
};

export type ChainedAsTokenConfig = {
  /**
   * Access token lifetime in seconds
   */
  lifetimeSeconds?: number;
  /**
   * Key ID for token signing
   */
  signingKeyId?: string;
};

export type ChainedAsConfig = {
  /**
   * Enable chained AS mode
   */
  enabled: boolean;
  /**
   * Upstream OIDC provider configuration
   */
  upstream?: UpstreamOidcConfig;
  /**
   * Token configuration
   */
  token?: ChainedAsTokenConfig;
  /**
   * Require DPoP binding for tokens
   */
  requireDPoP?: boolean;
};

export type IssuanceDto = {
  /**
   * Key ID for signing access tokens. If unset, the default signing key is used.
   */
  signingKeyId?: string;
  chainedAs?: ChainedAsConfig;
  /**
   * Whether refresh tokens should be issued for OID4VCI token responses.
   */
  refreshTokenEnabled?: boolean;
  /**
   * Whether `credential_response_encryption` should be advertised in the credential issuer metadata.
   */
  credentialResponseEncryption?: boolean;
  /**
   * Refresh token lifetime in seconds. Defaults to 2592000 (30 days).
   */
  refreshTokenExpiresInSeconds?: number;
};

export type CredentialConfigCreate = {
  /**
   * VCT as a URI string (e.g., urn:eudi:pid:de:1) or as an object for EUDIPLO-hosted VCT
   */
  vct: string | Vct;
  /**
   * List of IAE actions to execute before credential issuance
   */
  iaeActions?: Array<IaeActionOpenid4VpPresentation | IaeActionRedirectToWeb>;
  embeddedDisclosurePolicy:
    | AttestationBasedPolicy
    | NoneTrustPolicy
    | AllowListPolicy
    | RootOfTrustPolicy;
};

export type CredentialConfigUpdate = {
  /**
   * VCT as a URI string (e.g., urn:eudi:pid:de:1) or as an object for EUDIPLO-hosted VCT
   */
  vct?: string | Vct;
  /**
   * List of IAE actions to execute before credential issuance
   */
  iaeActions?: Array<IaeActionOpenid4VpPresentation | IaeActionRedirectToWeb>;
  embeddedDisclosurePolicy?:
    | AttestationBasedPolicy
    | NoneTrustPolicy
    | AllowListPolicy
    | RootOfTrustPolicy;
};

export type CreateAttributeProviderDto = {
  auth: WebHookAuthConfigNone | WebHookAuthConfigHeader;
};

export type UpdateAttributeProviderDto = {
  auth?: WebHookAuthConfigNone | WebHookAuthConfigHeader;
};

export type CreateWebhookEndpointDto = {
  auth: WebHookAuthConfigNone | WebHookAuthConfigHeader;
};

export type UpdateWebhookEndpointDto = {
  auth?: WebHookAuthConfigNone | WebHookAuthConfigHeader;
};

export type ResolveIssuerMetadataDto = {
  /**
   * Issuer URL or full OpenID4VCI metadata URL to resolve server-side.
   */
  issuerUrl: string;
};

export type PresentationConfigCreateDto = {
  [key: string]: unknown;
};

export type PresentationConfigUpdateDto = {
  [key: string]: unknown;
};

export type RegistrarConfigResponseDto = {
  /**
   * The base URL of the registrar API
   */
  registrarUrl: string;
  /**
   * The OIDC issuer URL for authentication (e.g., Keycloak realm URL)
   */
  oidcUrl: string;
  /**
   * The OIDC client ID for the registrar
   */
  clientId: string;
  /**
   * The OIDC client secret (optional, for confidential clients)
   */
  clientSecret?: string;
  /**
   * The username for OIDC login
   */
  username: string;
  /**
   * Optional default values merged into registration certificate creation requests (for example privacy_policy, support_uri, provided_attestations)
   */
  registrationCertificateDefaults?: {
    [key: string]: unknown;
  };
  /**
   * Indicates whether a password is configured (actual password is never returned)
   */
  hasPassword: boolean;
};

export type CreateRegistrarConfigDto = {
  /**
   * The base URL of the registrar API
   */
  registrarUrl: string;
  /**
   * The OIDC issuer URL for authentication (e.g., Keycloak realm URL)
   */
  oidcUrl: string;
  /**
   * The OIDC client ID for the registrar
   */
  clientId: string;
  /**
   * The OIDC client secret (optional, for confidential clients)
   */
  clientSecret?: string;
  /**
   * The username for OIDC login
   */
  username: string;
  /**
   * The password for OIDC login (stored in plaintext)
   */
  password: string;
  /**
   * Optional default values merged into registration certificate creation requests (for example privacy_policy, support_uri, provided_attestations)
   */
  registrationCertificateDefaults?: {
    [key: string]: unknown;
  };
};

export type UpdateRegistrarConfigDto = {
  /**
   * The base URL of the registrar API
   */
  registrarUrl?: string;
  /**
   * The OIDC issuer URL for authentication (e.g., Keycloak realm URL)
   */
  oidcUrl?: string;
  /**
   * The OIDC client ID for the registrar
   */
  clientId?: string;
  /**
   * The OIDC client secret (optional, for confidential clients)
   */
  clientSecret?: string;
  /**
   * The username for OIDC login
   */
  username?: string;
  /**
   * The password for OIDC login (stored in plaintext)
   */
  password?: string;
  /**
   * Optional default values merged into registration certificate creation requests (for example privacy_policy, support_uri, provided_attestations)
   */
  registrationCertificateDefaults?: {
    [key: string]: unknown;
  };
};

export type CreateAccessCertificateDto = {
  /**
   * The ID of the key to create an access certificate for
   */
  keyId: string;
};

export type DeferredCredentialRequestDto = {
  /**
   * The transaction identifier previously returned by the Credential Endpoint
   */
  transaction_id: string;
};

export type NotificationRequestDto = {
  [key: string]: unknown;
};

export type AuthorizeQueries = {
  [key: string]: unknown;
};

export type InteractiveAuthorizationRequestDto = {
  /**
   * Response type (for initial request)
   */
  response_type?: string;
  /**
   * Client identifier (for initial request)
   */
  client_id?: string;
  /**
   * Comma-separated list of supported interaction types (for initial request)
   */
  interaction_types_supported?: string;
  /**
   * Redirect URI (for initial request)
   */
  redirect_uri?: string;
  /**
   * OAuth scope
   */
  scope?: string;
  /**
   * PKCE code challenge
   */
  code_challenge?: string;
  /**
   * PKCE code challenge method
   */
  code_challenge_method?: string;
  /**
   * Authorization details
   */
  authorization_details?: {
    [key: string]: unknown;
  };
  /**
   * State parameter
   */
  state?: string;
  /**
   * Issuer state from credential offer
   */
  issuer_state?: string;
  /**
   * Auth session identifier (for follow-up request)
   */
  auth_session?: string;
  /**
   * OpenID4VP response (for follow-up request)
   */
  openid4vp_response?: string;
  /**
   * PKCE code verifier (for follow-up request)
   */
  code_verifier?: string;
  /**
   * JAR request JWT (by value)
   */
  request?: string;
  /**
   * JAR request URI (by reference)
   */
  request_uri?: string;
};

export type InteractiveAuthorizationCodeResponseDto = {
  /**
   * Response status
   */
  status: string;
  /**
   * Authorization code
   */
  code: string;
};

export type InteractiveAuthorizationErrorResponseDto = {
  /**
   * OAuth error code
   */
  error: string;
  /**
   * Human-readable error description
   */
  error_description?: string;
};

export type ChainedAsParResponseDto = {
  /**
   * The request URI to use at the authorization endpoint
   */
  request_uri: string;
  /**
   * The lifetime of the request URI in seconds
   */
  expires_in: number;
};

export type ChainedAsErrorResponseDto = {
  /**
   * Error code
   */
  error: string;
  /**
   * Human-readable error description
   */
  error_description?: string;
};

export type ChainedAsTokenRequestDto = {
  /**
   * Grant type ('authorization_code' or 'refresh_token')
   */
  grant_type: string;
  /**
   * Authorization code received in the callback (authorization_code grant)
   */
  code?: string;
  /**
   * Refresh token (refresh_token grant)
   */
  refresh_token?: string;
  /**
   * Client identifier
   */
  client_id?: string;
  /**
   * Redirect URI (must match the one used in PAR)
   */
  redirect_uri?: string;
  /**
   * PKCE code verifier
   */
  code_verifier?: string;
};

export type ChainedAsTokenResponseDto = {
  /**
   * The access token
   */
  access_token: string;
  /**
   * Token type (Bearer or DPoP)
   */
  token_type: string;
  /**
   * Token lifetime in seconds
   */
  expires_in: number;
  /**
   * Scope granted
   */
  scope?: string;
  /**
   * Authorized credential configurations
   */
  authorization_details?: Array<string>;
  /**
   * C_NONCE for credential request
   */
  c_nonce?: string;
  /**
   * C_NONCE lifetime in seconds
   */
  c_nonce_expires_in?: number;
  /**
   * Refresh token (issued when refresh tokens are enabled)
   */
  refresh_token?: string;
};

export type OfferRequestDto = {
  /**
   * The type of response expected for the offer request.
   */
  response_type: "uri" | "dc-api";
  /**
   * Credential claims configuration per credential. Keys must match credentialConfigurationIds.
   */
  credentialClaims: {
    additionalProperties?:
      | {
          type: "inline";
          claims: {
            [key: string]: unknown;
          };
        }
      | {
          type: "attributeProvider";
          attributeProviderId: string;
        }
      | {
          type: "webhook";
          webhook: {
            url: string;
            auth?: {
              [key: string]: unknown;
            };
          };
        };
  };
};

export type OfferResponse = {
  [key: string]: unknown;
};

export type CompleteDeferredDto = {
  /**
   * Claims to include in the credential. The structure should match the credential configuration's expected claims.
   */
  claims: {
    [key: string]: unknown;
  };
};

export type DeferredOperationResponse = {
  /**
   * The transaction ID
   */
  transactionId: string;
  /**
   * The new status of the transaction
   */
  status: "pending" | "ready" | "retrieved" | "expired" | "failed";
  /**
   * Optional message
   */
  message?: string;
};

export type FailDeferredDto = {
  /**
   * Optional error message explaining why the issuance failed
   */
  error?: string;
};

export type AuthorizationResponse = {
  [key: string]: unknown;
};

export type InternalTrustListEntity = {
  type: "internal";
};

export type ExternalTrustListEntity = {
  type: "external";
};

export type TrustListCreateDto = {
  entities: Array<
    | ({
        type: "internal";
      } & InternalTrustListEntity)
    | ({
        type: "external";
      } & ExternalTrustListEntity)
  >;
};

export type KmsProviderCapabilitiesDto = {
  /**
   * Whether the provider supports importing existing keys.
   */
  canImport: boolean;
  /**
   * Whether the provider supports generating new keys.
   */
  canCreate: boolean;
  /**
   * Whether the provider supports deleting keys.
   */
  canDelete: boolean;
};

export type KmsProviderInfoDto = {
  /**
   * Unique provider ID (matches the id in kms.json).
   */
  name: string;
  /**
   * Type of the KMS provider (db, vault, aws-kms).
   */
  type: string;
  /**
   * Human-readable description of this provider instance.
   */
  description?: string;
  /**
   * Capabilities of this provider.
   */
  capabilities: KmsProviderCapabilitiesDto;
};

export type KmsProvidersResponseDto = {
  /**
   * Detailed info for each registered KMS provider.
   */
  providers: Array<KmsProviderInfoDto>;
  /**
   * The default KMS provider name.
   */
  default: string;
};

export type CertificateInfoDto = {
  /**
   * Certificate in PEM format.
   */
  pem: string;
  /**
   * Certificate subject (CN).
   */
  subject?: string;
  /**
   * Certificate issuer (CN).
   */
  issuer?: string;
  /**
   * Certificate not before date.
   */
  notBefore?: string;
  /**
   * Certificate not after date.
   */
  notAfter?: string;
  /**
   * Serial number.
   */
  serialNumber?: string;
};

export type PublicKeyInfoDto = {
  /**
   * Key type (e.g., EC).
   */
  kty: string;
  /**
   * Key algorithm (e.g., ES256).
   */
  alg?: string;
  /**
   * Key ID.
   */
  kid?: string;
  /**
   * Curve (for EC keys).
   */
  crv?: string;
};

export type RotationPolicyResponseDto = {
  /**
   * Whether automatic key rotation is enabled.
   */
  enabled: boolean;
  /**
   * Rotation interval in days.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days.
   */
  certValidityDays?: number;
  /**
   * Next scheduled rotation date.
   */
  nextRotationAt?: string;
};

export type KeyChainResponseDto = {
  /**
   * Unique identifier for the key chain.
   */
  id: string;
  /**
   * Usage type of the key chain.
   */
  usageType: "access" | "attestation" | "trustList" | "statusList" | "encrypt";
  /**
   * Type of key chain (standalone or internalChain).
   */
  type: "standalone" | "internalChain";
  /**
   * Human-readable description.
   */
  description?: string;
  /**
   * KMS provider used for this key chain.
   */
  kmsProvider: string;
  /**
   * Root CA certificate (only for internalChain type).
   */
  rootCertificate?: CertificateInfoDto;
  /**
   * Active signing key's public key info.
   */
  activePublicKey: PublicKeyInfoDto;
  /**
   * Active signing key's certificate. Not present for encryption keys.
   */
  activeCertificate?: CertificateInfoDto;
  /**
   * Previous signing key's public key info (if in grace period).
   */
  previousPublicKey?: PublicKeyInfoDto;
  /**
   * Previous signing key's certificate (if in grace period).
   */
  previousCertificate?: CertificateInfoDto;
  /**
   * Previous key expiry date.
   */
  previousKeyExpiry?: string;
  /**
   * Rotation policy configuration.
   */
  rotationPolicy: RotationPolicyResponseDto;
  /**
   * Timestamp when the key chain was created.
   */
  createdAt: string;
  /**
   * Timestamp when the key chain was last updated.
   */
  updatedAt: string;
};

export type ExportEcJwk = {
  /**
   * Key type
   */
  kty: string;
  /**
   * Curve
   */
  crv: string;
  /**
   * X coordinate (base64url)
   */
  x: string;
  /**
   * Y coordinate (base64url)
   */
  y: string;
  /**
   * Private key (base64url)
   */
  d: string;
  /**
   * Algorithm
   */
  alg?: string;
  /**
   * Key ID
   */
  kid?: string;
};

export type ExportRotationPolicyDto = {
  /**
   * Whether rotation is enabled.
   */
  enabled: boolean;
  /**
   * Rotation interval in days.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days.
   */
  certValidityDays?: number;
};

export type KeyChainExportDto = {
  /**
   * Key chain ID.
   */
  id: string;
  /**
   * Human-readable description.
   */
  description?: string;
  /**
   * Usage type for this key chain.
   */
  usageType: "access" | "attestation" | "trustList" | "statusList" | "encrypt";
  /**
   * The private key in JWK format (EC).
   */
  key: ExportEcJwk;
  /**
   * Certificate chain in PEM format (leaf first, then intermediates/CA).
   */
  crt?: Array<string>;
  /**
   * KMS provider name.
   */
  kmsProvider?: string;
  /**
   * Rotation policy.
   */
  rotationPolicy?: ExportRotationPolicyDto;
};

export type RotationPolicyCreateDto = {
  /**
   * Whether automatic key rotation is enabled.
   */
  enabled: boolean;
  /**
   * Rotation interval in days. Required when enabled is true.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days. Defaults to rotation interval + 30 days grace period.
   */
  certValidityDays?: number;
};

export type KeyChainCreateDto = {
  /**
   * Usage type determines the purpose of this key chain (access, attestation, etc.).
   */
  usageType: "access" | "attestation" | "trustList" | "statusList" | "encrypt";
  /**
   * Type of key chain to create.
   */
  type: "standalone" | "internalChain";
  /**
   * Human-readable description for the key chain.
   */
  description?: string;
  /**
   * KMS provider to use (defaults to the configured default provider).
   */
  kmsProvider?: string;
  /**
   * Rotation policy configuration. Only applicable for the signing key (root CA never rotates).
   */
  rotationPolicy?: RotationPolicyCreateDto;
};

export type EcJwk = {
  [key: string]: unknown;
};

export type RotationPolicyImportDto = {
  /**
   * Whether rotation is enabled. When true, the imported key becomes a root CA.
   */
  enabled: boolean;
  /**
   * Rotation interval in days.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days.
   */
  certValidityDays?: number;
};

export type KeyChainImportDto = {
  /**
   * ID for the key chain. If not provided, a new UUID will be generated.
   */
  id?: string;
  /**
   * The private key in JWK format.
   */
  key: EcJwk;
  /**
   * Human-readable description.
   */
  description?: string;
  /**
   * Usage type for this key chain.
   */
  usageType: "access" | "attestation" | "trustList" | "statusList" | "encrypt";
  /**
   * Certificate chain in PEM format (leaf first, then intermediates/CA).
   */
  crt?: Array<string>;
  /**
   * KMS provider to use. Defaults to 'db'.
   */
  kmsProvider?: string;
  /**
   * Rotation policy. When enabled, the imported key becomes a root CA and a new leaf key is generated.
   */
  rotationPolicy?: RotationPolicyImportDto;
};

export type RotationPolicyUpdateDto = {
  /**
   * Whether automatic key rotation is enabled.
   */
  enabled?: boolean;
  /**
   * Rotation interval in days.
   */
  intervalDays?: number;
  /**
   * Certificate validity in days.
   */
  certValidityDays?: number;
};

export type KeyChainUpdateDto = {
  /**
   * Human-readable description for the key chain.
   */
  description?: string;
  /**
   * Rotation policy configuration.
   */
  rotationPolicy?: RotationPolicyUpdateDto;
  /**
   * Active certificate chain in PEM format. Used for external certificate updates.
   */
  activeCertificate?: string;
};

export type PresentationRequest = {
  [key: string]: unknown;
};

export type FileUploadDto = {
  file: Blob | File;
};

/**
 * Auto-generated fallback schema to satisfy an unresolved local $ref in the OpenAPI document.
 */
export type WebHookAuthConfigHeader = {
  [key: string]: unknown;
};

/**
 * Auto-generated fallback schema to satisfy an unresolved local $ref in the OpenAPI document.
 */
export type WebHookAuthConfigNone = {
  [key: string]: unknown;
};

/**
 * Auto-generated fallback schema to satisfy an unresolved local $ref in the OpenAPI document.
 */
export type RootOfTrustPolicy = {
  [key: string]: unknown;
};

/**
 * Auto-generated fallback schema to satisfy an unresolved local $ref in the OpenAPI document.
 */
export type AllowListPolicy = {
  [key: string]: unknown;
};

/**
 * Auto-generated fallback schema to satisfy an unresolved local $ref in the OpenAPI document.
 */
export type NoneTrustPolicy = {
  [key: string]: unknown;
};

/**
 * Auto-generated fallback schema to satisfy an unresolved local $ref in the OpenAPI document.
 */
export type AttestationBasedPolicy = {
  [key: string]: unknown;
};

/**
 * Auto-generated fallback schema to satisfy an unresolved local $ref in the OpenAPI document.
 */
export type IaeActionRedirectToWeb = {
  [key: string]: unknown;
};

/**
 * Auto-generated fallback schema to satisfy an unresolved local $ref in the OpenAPI document.
 */
export type IaeActionOpenid4VpPresentation = {
  [key: string]: unknown;
};

/**
 * Auto-generated fallback schema to satisfy an unresolved local $ref in the OpenAPI document.
 */
export type Vct = {
  [key: string]: unknown;
};

export type AppControllerGetVersionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/version";
};

export type AppControllerGetVersionResponses = {
  /**
   * Service version info
   */
  200: unknown;
};

export type AppControllerGetFrontendConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/frontend-config";
};

export type AppControllerGetFrontendConfigResponses = {
  /**
   * Frontend configuration
   */
  200: FrontendConfigResponseDto;
};

export type AppControllerGetFrontendConfigResponse =
  AppControllerGetFrontendConfigResponses[keyof AppControllerGetFrontendConfigResponses];

export type TenantControllerGetTenantsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/tenant";
};

export type TenantControllerGetTenantsResponses = {
  200: unknown;
};

export type TenantControllerInitTenantData = {
  body: CreateTenantDto;
  path?: never;
  query?: never;
  url: "/api/tenant";
};

export type TenantControllerInitTenantResponses = {
  201: unknown;
};

export type TenantControllerDeleteTenantData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tenant/{id}";
};

export type TenantControllerDeleteTenantResponses = {
  200: unknown;
};

export type TenantControllerGetTenantData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tenant/{id}";
};

export type TenantControllerGetTenantResponses = {
  200: unknown;
};

export type TenantControllerUpdateTenantData = {
  body: UpdateTenantDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tenant/{id}";
};

export type TenantControllerUpdateTenantResponses = {
  200: unknown;
};

export type ClientControllerGetClientsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/client";
};

export type ClientControllerGetClientsResponses = {
  200: unknown;
};

export type ClientControllerCreateClientData = {
  body: CreateClientDto;
  path?: never;
  query?: never;
  url: "/api/client";
};

export type ClientControllerCreateClientResponses = {
  201: unknown;
};

export type ClientControllerDeleteClientData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}";
};

export type ClientControllerDeleteClientResponses = {
  200: unknown;
};

export type ClientControllerGetClientData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}";
};

export type ClientControllerGetClientResponses = {
  200: unknown;
};

export type ClientControllerUpdateClientData = {
  body: UpdateClientDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}";
};

export type ClientControllerUpdateClientResponses = {
  200: unknown;
};

export type ClientControllerGetClientSecretData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}/secret";
};

export type ClientControllerGetClientSecretResponses = {
  200: unknown;
};

export type ClientControllerRotateClientSecretData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/client/{id}/rotate-secret";
};

export type ClientControllerRotateClientSecretResponses = {
  201: unknown;
};

export type StatusListConfigControllerResetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/status-list-config";
};

export type StatusListConfigControllerResetConfigResponses = {
  /**
   * Configuration reset successfully
   */
  204: void;
};

export type StatusListConfigControllerResetConfigResponse =
  StatusListConfigControllerResetConfigResponses[keyof StatusListConfigControllerResetConfigResponses];

export type StatusListConfigControllerGetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/status-list-config";
};

export type StatusListConfigControllerGetConfigResponses = {
  /**
   * The status list configuration
   */
  200: StatusListConfig;
};

export type StatusListConfigControllerGetConfigResponse =
  StatusListConfigControllerGetConfigResponses[keyof StatusListConfigControllerGetConfigResponses];

export type StatusListConfigControllerUpdateConfigData = {
  body: UpdateStatusListConfigDto;
  path?: never;
  query?: never;
  url: "/api/status-list-config";
};

export type StatusListConfigControllerUpdateConfigResponses = {
  /**
   * The updated status list configuration
   */
  200: StatusListConfig;
};

export type StatusListConfigControllerUpdateConfigResponse =
  StatusListConfigControllerUpdateConfigResponses[keyof StatusListConfigControllerUpdateConfigResponses];

export type StatusListManagementControllerGetListsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/status-lists";
};

export type StatusListManagementControllerGetListsResponses = {
  /**
   * List of status lists
   */
  200: Array<StatusListResponseDto>;
};

export type StatusListManagementControllerGetListsResponse =
  StatusListManagementControllerGetListsResponses[keyof StatusListManagementControllerGetListsResponses];

export type StatusListManagementControllerCreateListData = {
  body: CreateStatusListDto;
  path?: never;
  query?: never;
  url: "/api/status-lists";
};

export type StatusListManagementControllerCreateListResponses = {
  /**
   * The created status list
   */
  201: StatusListResponseDto;
};

export type StatusListManagementControllerCreateListResponse =
  StatusListManagementControllerCreateListResponses[keyof StatusListManagementControllerCreateListResponses];

export type StatusListManagementControllerDeleteListData = {
  body?: never;
  path: {
    /**
     * The status list ID
     */
    listId: string;
  };
  query?: never;
  url: "/api/status-lists/{listId}";
};

export type StatusListManagementControllerDeleteListResponses = {
  /**
   * Status list deleted successfully
   */
  204: void;
};

export type StatusListManagementControllerDeleteListResponse =
  StatusListManagementControllerDeleteListResponses[keyof StatusListManagementControllerDeleteListResponses];

export type StatusListManagementControllerGetListData = {
  body?: never;
  path: {
    /**
     * The status list ID
     */
    listId: string;
  };
  query?: never;
  url: "/api/status-lists/{listId}";
};

export type StatusListManagementControllerGetListResponses = {
  /**
   * The status list
   */
  200: StatusListResponseDto;
};

export type StatusListManagementControllerGetListResponse =
  StatusListManagementControllerGetListResponses[keyof StatusListManagementControllerGetListResponses];

export type StatusListManagementControllerUpdateListData = {
  body: UpdateStatusListDto;
  path: {
    /**
     * The status list ID
     */
    listId: string;
  };
  query?: never;
  url: "/api/status-lists/{listId}";
};

export type StatusListManagementControllerUpdateListResponses = {
  /**
   * The updated status list
   */
  200: StatusListResponseDto;
};

export type StatusListManagementControllerUpdateListResponse =
  StatusListManagementControllerUpdateListResponses[keyof StatusListManagementControllerUpdateListResponses];

export type SessionControllerGetAllSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/session";
};

export type SessionControllerGetAllSessionsResponses = {
  200: unknown;
};

export type SessionControllerDeleteSessionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/session/{id}";
};

export type SessionControllerDeleteSessionResponses = {
  200: unknown;
};

export type SessionControllerGetSessionData = {
  body?: never;
  path: {
    /**
     * The session ID
     */
    id: string;
  };
  query?: never;
  url: "/api/session/{id}";
};

export type SessionControllerGetSessionResponses = {
  200: unknown;
};

export type SessionControllerGetSessionLogsData = {
  body?: never;
  path: {
    /**
     * The session ID
     */
    id: string;
  };
  query?: never;
  url: "/api/session/{id}/logs";
};

export type SessionControllerGetSessionLogsResponses = {
  200: Array<SessionLogEntryResponseDto>;
};

export type SessionControllerGetSessionLogsResponse =
  SessionControllerGetSessionLogsResponses[keyof SessionControllerGetSessionLogsResponses];

export type SessionControllerRevokeAllData = {
  body: StatusUpdateDto;
  path?: never;
  query?: never;
  url: "/api/session/revoke";
};

export type SessionControllerRevokeAllResponses = {
  201: unknown;
};

export type SessionConfigControllerResetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/session-config";
};

export type SessionConfigControllerResetConfigResponses = {
  /**
   * Configuration reset successfully
   */
  200: unknown;
};

export type SessionConfigControllerGetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/session-config";
};

export type SessionConfigControllerGetConfigResponses = {
  /**
   * The session storage configuration
   */
  200: SessionStorageConfig;
};

export type SessionConfigControllerGetConfigResponse =
  SessionConfigControllerGetConfigResponses[keyof SessionConfigControllerGetConfigResponses];

export type SessionConfigControllerUpdateConfigData = {
  body: UpdateSessionConfigDto;
  path?: never;
  query?: never;
  url: "/api/session-config";
};

export type SessionConfigControllerUpdateConfigResponses = {
  /**
   * The updated session storage configuration
   */
  200: SessionStorageConfig;
};

export type SessionConfigControllerUpdateConfigResponse =
  SessionConfigControllerUpdateConfigResponses[keyof SessionConfigControllerUpdateConfigResponses];

export type SessionEventsControllerSubscribeToSessionEventsData = {
  body?: never;
  path: {
    /**
     * Session ID to subscribe to
     */
    id: string;
  };
  query: {
    /**
     * JWT access token for authentication
     */
    token: string;
  };
  url: "/api/session/{id}/events";
};

export type SessionEventsControllerSubscribeToSessionEventsResponses = {
  200: unknown;
};

export type UserControllerGetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/user";
};

export type UserControllerGetUsersResponses = {
  200: Array<ManagedUserDto>;
};

export type UserControllerGetUsersResponse =
  UserControllerGetUsersResponses[keyof UserControllerGetUsersResponses];

export type UserControllerCreateUserData = {
  body: CreateUserDto;
  path?: never;
  query?: never;
  url: "/api/user";
};

export type UserControllerCreateUserResponses = {
  201: ManagedUserDto;
};

export type UserControllerCreateUserResponse =
  UserControllerCreateUserResponses[keyof UserControllerCreateUserResponses];

export type UserControllerDeleteUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/user/{id}";
};

export type UserControllerDeleteUserResponses = {
  200: unknown;
};

export type UserControllerGetUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/user/{id}";
};

export type UserControllerGetUserResponses = {
  200: ManagedUserDto;
};

export type UserControllerGetUserResponse =
  UserControllerGetUserResponses[keyof UserControllerGetUserResponses];

export type UserControllerUpdateUserData = {
  body: UpdateUserDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/user/{id}";
};

export type UserControllerUpdateUserResponses = {
  200: ManagedUserDto;
};

export type UserControllerUpdateUserResponse =
  UserControllerUpdateUserResponses[keyof UserControllerUpdateUserResponses];

export type IssuanceConfigControllerGetIssuanceConfigurationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/issuer/config";
};

export type IssuanceConfigControllerGetIssuanceConfigurationsResponses = {
  200: unknown;
};

export type IssuanceConfigControllerStoreIssuanceConfigurationData = {
  body: IssuanceDto;
  path?: never;
  query?: never;
  url: "/api/issuer/config";
};

export type IssuanceConfigControllerStoreIssuanceConfigurationResponses = {
  201: unknown;
};

export type CredentialConfigControllerGetConfigsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/issuer/credentials";
};

export type CredentialConfigControllerGetConfigsResponses = {
  200: unknown;
};

export type CredentialConfigControllerStoreCredentialConfigurationData = {
  body: CredentialConfigCreate;
  path?: never;
  query?: never;
  url: "/api/issuer/credentials";
};

export type CredentialConfigControllerStoreCredentialConfigurationResponses = {
  201: unknown;
};

export type CredentialConfigControllerDeleteIssuanceConfigurationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/credentials/{id}";
};

export type CredentialConfigControllerDeleteIssuanceConfigurationResponses = {
  200: unknown;
};

export type CredentialConfigControllerGetConfigByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/credentials/{id}";
};

export type CredentialConfigControllerGetConfigByIdResponses = {
  200: unknown;
};

export type CredentialConfigControllerUpdateCredentialConfigurationData = {
  body: CredentialConfigUpdate;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/credentials/{id}";
};

export type CredentialConfigControllerUpdateCredentialConfigurationResponses = {
  200: unknown;
};

export type AttributeProviderControllerGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/issuer/attribute-providers";
};

export type AttributeProviderControllerGetAllResponses = {
  /**
   * List of attribute providers
   */
  200: unknown;
};

export type AttributeProviderControllerCreateData = {
  body: CreateAttributeProviderDto;
  path?: never;
  query?: never;
  url: "/api/issuer/attribute-providers";
};

export type AttributeProviderControllerCreateResponses = {
  /**
   * Attribute provider created
   */
  201: unknown;
};

export type AttributeProviderControllerDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/attribute-providers/{id}";
};

export type AttributeProviderControllerDeleteErrors = {
  /**
   * Attribute provider not found
   */
  404: unknown;
};

export type AttributeProviderControllerDeleteResponses = {
  /**
   * Attribute provider deleted
   */
  200: unknown;
};

export type AttributeProviderControllerGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/attribute-providers/{id}";
};

export type AttributeProviderControllerGetByIdErrors = {
  /**
   * Attribute provider not found
   */
  404: unknown;
};

export type AttributeProviderControllerGetByIdResponses = {
  /**
   * The attribute provider
   */
  200: unknown;
};

export type AttributeProviderControllerUpdateData = {
  body: UpdateAttributeProviderDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/attribute-providers/{id}";
};

export type AttributeProviderControllerUpdateErrors = {
  /**
   * Attribute provider not found
   */
  404: unknown;
};

export type AttributeProviderControllerUpdateResponses = {
  /**
   * Attribute provider updated
   */
  200: unknown;
};

export type WebhookEndpointControllerGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/issuer/webhook-endpoints";
};

export type WebhookEndpointControllerGetAllResponses = {
  /**
   * List of webhook endpoints
   */
  200: unknown;
};

export type WebhookEndpointControllerCreateData = {
  body: CreateWebhookEndpointDto;
  path?: never;
  query?: never;
  url: "/api/issuer/webhook-endpoints";
};

export type WebhookEndpointControllerCreateResponses = {
  /**
   * Webhook endpoint created
   */
  201: unknown;
};

export type WebhookEndpointControllerDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/webhook-endpoints/{id}";
};

export type WebhookEndpointControllerDeleteErrors = {
  /**
   * Webhook endpoint not found
   */
  404: unknown;
};

export type WebhookEndpointControllerDeleteResponses = {
  /**
   * Webhook endpoint deleted
   */
  200: unknown;
};

export type WebhookEndpointControllerGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/webhook-endpoints/{id}";
};

export type WebhookEndpointControllerGetByIdErrors = {
  /**
   * Webhook endpoint not found
   */
  404: unknown;
};

export type WebhookEndpointControllerGetByIdResponses = {
  /**
   * The webhook endpoint
   */
  200: unknown;
};

export type WebhookEndpointControllerUpdateData = {
  body: UpdateWebhookEndpointDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/issuer/webhook-endpoints/{id}";
};

export type WebhookEndpointControllerUpdateErrors = {
  /**
   * Webhook endpoint not found
   */
  404: unknown;
};

export type WebhookEndpointControllerUpdateResponses = {
  /**
   * Webhook endpoint updated
   */
  200: unknown;
};

export type PresentationManagementControllerConfigurationData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/verifier/config";
};

export type PresentationManagementControllerConfigurationResponses = {
  200: unknown;
};

export type PresentationManagementControllerStorePresentationConfigData = {
  body: PresentationConfigCreateDto;
  path?: never;
  query?: never;
  url: "/api/verifier/config";
};

export type PresentationManagementControllerStorePresentationConfigResponses = {
  201: unknown;
};

export type PresentationManagementControllerResolveIssuerMetadataData = {
  body: ResolveIssuerMetadataDto;
  path?: never;
  query?: never;
  url: "/api/verifier/config/issuer-metadata/resolve";
};

export type PresentationManagementControllerResolveIssuerMetadataErrors = {
  /**
   * Invalid issuer URL or metadata could not be resolved
   */
  400: unknown;
};

export type PresentationManagementControllerResolveIssuerMetadataResponses = {
  /**
   * Resolved credential issuer metadata
   */
  200: unknown;
};

export type PresentationManagementControllerDeleteConfigurationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/verifier/config/{id}";
};

export type PresentationManagementControllerDeleteConfigurationResponses = {
  200: unknown;
};

export type PresentationManagementControllerGetConfigurationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/verifier/config/{id}";
};

export type PresentationManagementControllerGetConfigurationResponses = {
  200: unknown;
};

export type PresentationManagementControllerUpdateConfigurationData = {
  body: PresentationConfigUpdateDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/verifier/config/{id}";
};

export type PresentationManagementControllerUpdateConfigurationResponses = {
  200: unknown;
};

export type PresentationManagementControllerReissueRegistrationCertificateData =
  {
    body?: never;
    path: {
      id: string;
    };
    query?: never;
    url: "/api/verifier/config/{id}/registration-cert/reissue";
  };

export type PresentationManagementControllerReissueRegistrationCertificateErrors =
  {
    /**
     * Config has no registrationCert spec or registrar is not enabled
     */
    400: unknown;
  };

export type PresentationManagementControllerReissueRegistrationCertificateResponses =
  {
    /**
     * Updated presentation configuration
     */
    200: unknown;
  };

export type CacheControllerGetStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/cache/stats";
};

export type CacheControllerGetStatsResponses = {
  /**
   * Cache statistics
   */
  200: unknown;
};

export type CacheControllerClearAllCachesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/cache";
};

export type CacheControllerClearAllCachesResponses = {
  /**
   * All caches cleared successfully
   */
  204: void;
};

export type CacheControllerClearAllCachesResponse =
  CacheControllerClearAllCachesResponses[keyof CacheControllerClearAllCachesResponses];

export type CacheControllerClearTrustListCacheData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/cache/trust-list";
};

export type CacheControllerClearTrustListCacheResponses = {
  /**
   * Trust list cache cleared successfully
   */
  204: void;
};

export type CacheControllerClearTrustListCacheResponse =
  CacheControllerClearTrustListCacheResponses[keyof CacheControllerClearTrustListCacheResponses];

export type CacheControllerClearStatusListCacheData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/cache/status-list";
};

export type CacheControllerClearStatusListCacheResponses = {
  /**
   * Status list cache cleared successfully
   */
  204: void;
};

export type CacheControllerClearStatusListCacheResponse =
  CacheControllerClearStatusListCacheResponses[keyof CacheControllerClearStatusListCacheResponses];

export type RegistrarControllerDeleteConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/registrar/config";
};

export type RegistrarControllerDeleteConfigResponses = {
  /**
   * Configuration deleted successfully
   */
  204: void;
};

export type RegistrarControllerDeleteConfigResponse =
  RegistrarControllerDeleteConfigResponses[keyof RegistrarControllerDeleteConfigResponses];

export type RegistrarControllerGetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/registrar/config";
};

export type RegistrarControllerGetConfigErrors = {
  /**
   * No registrar configuration found
   */
  404: unknown;
};

export type RegistrarControllerGetConfigResponses = {
  /**
   * The registrar configuration
   */
  200: RegistrarConfigResponseDto;
};

export type RegistrarControllerGetConfigResponse =
  RegistrarControllerGetConfigResponses[keyof RegistrarControllerGetConfigResponses];

export type RegistrarControllerUpdateConfigData = {
  body: UpdateRegistrarConfigDto;
  path?: never;
  query?: never;
  url: "/api/registrar/config";
};

export type RegistrarControllerUpdateConfigErrors = {
  /**
   * Invalid credentials
   */
  400: unknown;
  /**
   * No registrar configuration found
   */
  404: unknown;
};

export type RegistrarControllerUpdateConfigResponses = {
  /**
   * Configuration updated successfully
   */
  200: RegistrarConfigResponseDto;
};

export type RegistrarControllerUpdateConfigResponse =
  RegistrarControllerUpdateConfigResponses[keyof RegistrarControllerUpdateConfigResponses];

export type RegistrarControllerCreateConfigData = {
  body: CreateRegistrarConfigDto;
  path?: never;
  query?: never;
  url: "/api/registrar/config";
};

export type RegistrarControllerCreateConfigErrors = {
  /**
   * Invalid credentials
   */
  400: unknown;
};

export type RegistrarControllerCreateConfigResponses = {
  /**
   * Configuration created successfully
   */
  201: RegistrarConfigResponseDto;
};

export type RegistrarControllerCreateConfigResponse =
  RegistrarControllerCreateConfigResponses[keyof RegistrarControllerCreateConfigResponses];

export type RegistrarControllerCreateAccessCertificateData = {
  body: CreateAccessCertificateDto;
  path?: never;
  query?: never;
  url: "/api/registrar/access-certificate";
};

export type RegistrarControllerCreateAccessCertificateErrors = {
  /**
   * No relying party found at registrar or failed to create certificate
   */
  400: unknown;
  /**
   * No registrar configuration found or key not found
   */
  404: unknown;
};

export type RegistrarControllerCreateAccessCertificateResponses = {
  /**
   * Access certificate created successfully
   */
  201: {
    /**
     * The certificate ID at the registrar
     */
    id?: string;
    /**
     * The certificate in PEM format
     */
    crt?: string;
  };
};

export type RegistrarControllerCreateAccessCertificateResponse =
  RegistrarControllerCreateAccessCertificateResponses[keyof RegistrarControllerCreateAccessCertificateResponses];

export type CredentialOfferControllerGetOfferData = {
  body: OfferRequestDto;
  path?: never;
  query?: never;
  url: "/api/issuer/offer";
};

export type CredentialOfferControllerGetOfferResponses = {
  /**
   * JSON response
   */
  201: OfferResponse;
};

export type CredentialOfferControllerGetOfferResponse =
  CredentialOfferControllerGetOfferResponses[keyof CredentialOfferControllerGetOfferResponses];

export type DeferredControllerCompleteDeferredData = {
  body: CompleteDeferredDto;
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/api/issuer/deferred/{transactionId}/complete";
};

export type DeferredControllerCompleteDeferredErrors = {
  /**
   * Transaction not found
   */
  404: unknown;
};

export type DeferredControllerCompleteDeferredResponses = {
  /**
   * Transaction completed successfully
   */
  200: DeferredOperationResponse;
};

export type DeferredControllerCompleteDeferredResponse =
  DeferredControllerCompleteDeferredResponses[keyof DeferredControllerCompleteDeferredResponses];

export type DeferredControllerFailDeferredData = {
  body?: FailDeferredDto;
  path: {
    transactionId: string;
  };
  query?: never;
  url: "/api/issuer/deferred/{transactionId}/fail";
};

export type DeferredControllerFailDeferredErrors = {
  /**
   * Transaction not found
   */
  404: unknown;
};

export type DeferredControllerFailDeferredResponses = {
  /**
   * Transaction marked as failed
   */
  200: DeferredOperationResponse;
};

export type DeferredControllerFailDeferredResponse =
  DeferredControllerFailDeferredResponses[keyof DeferredControllerFailDeferredResponses];

export type TrustListControllerGetAllTrustListsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/trust-list";
};

export type TrustListControllerGetAllTrustListsResponses = {
  200: unknown;
};

export type TrustListControllerCreateTrustListData = {
  body: TrustListCreateDto;
  path?: never;
  query?: never;
  url: "/api/trust-list";
};

export type TrustListControllerCreateTrustListResponses = {
  201: unknown;
};

export type TrustListControllerDeleteTrustListData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}";
};

export type TrustListControllerDeleteTrustListResponses = {
  200: unknown;
};

export type TrustListControllerGetTrustListData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}";
};

export type TrustListControllerGetTrustListResponses = {
  200: unknown;
};

export type TrustListControllerUpdateTrustListData = {
  body: TrustListCreateDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}";
};

export type TrustListControllerUpdateTrustListResponses = {
  200: unknown;
};

export type TrustListControllerExportTrustListData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}/export";
};

export type TrustListControllerExportTrustListResponses = {
  200: unknown;
};

export type TrustListControllerGetTrustListVersionsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/trust-list/{id}/versions";
};

export type TrustListControllerGetTrustListVersionsResponses = {
  200: unknown;
};

export type TrustListControllerGetTrustListVersionData = {
  body?: never;
  path: {
    id: string;
    versionId: string;
  };
  query?: never;
  url: "/api/trust-list/{id}/versions/{versionId}";
};

export type TrustListControllerGetTrustListVersionResponses = {
  200: unknown;
};

export type KeyChainControllerGetProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/key-chain/providers";
};

export type KeyChainControllerGetProvidersResponses = {
  /**
   * List of available KMS providers with capabilities
   */
  200: KmsProvidersResponseDto;
};

export type KeyChainControllerGetProvidersResponse =
  KeyChainControllerGetProvidersResponses[keyof KeyChainControllerGetProvidersResponses];

export type KeyChainControllerGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/key-chain";
};

export type KeyChainControllerGetAllResponses = {
  /**
   * List of key chains
   */
  200: Array<KeyChainResponseDto>;
};

export type KeyChainControllerGetAllResponse =
  KeyChainControllerGetAllResponses[keyof KeyChainControllerGetAllResponses];

export type KeyChainControllerCreateData = {
  body: KeyChainCreateDto;
  path?: never;
  query?: never;
  url: "/api/key-chain";
};

export type KeyChainControllerCreateResponses = {
  /**
   * Key chain created successfully
   */
  201: unknown;
};

export type KeyChainControllerDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}";
};

export type KeyChainControllerDeleteErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerDeleteResponses = {
  /**
   * Key chain deleted successfully
   */
  200: unknown;
};

export type KeyChainControllerGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}";
};

export type KeyChainControllerGetByIdErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerGetByIdResponses = {
  /**
   * The key chain
   */
  200: KeyChainResponseDto;
};

export type KeyChainControllerGetByIdResponse =
  KeyChainControllerGetByIdResponses[keyof KeyChainControllerGetByIdResponses];

export type KeyChainControllerUpdateData = {
  body: KeyChainUpdateDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}";
};

export type KeyChainControllerUpdateErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerUpdateResponses = {
  /**
   * Key chain updated successfully
   */
  200: unknown;
};

export type KeyChainControllerExportData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}/export";
};

export type KeyChainControllerExportErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerExportResponses = {
  /**
   * Key chain export data
   */
  200: KeyChainExportDto;
};

export type KeyChainControllerExportResponse =
  KeyChainControllerExportResponses[keyof KeyChainControllerExportResponses];

export type KeyChainControllerImportData = {
  body: KeyChainImportDto;
  path?: never;
  query?: never;
  url: "/api/key-chain/import";
};

export type KeyChainControllerImportResponses = {
  /**
   * Key chain imported successfully
   */
  201: unknown;
};

export type KeyChainControllerRotateData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/key-chain/{id}/rotate";
};

export type KeyChainControllerRotateErrors = {
  /**
   * Key chain not found
   */
  404: unknown;
};

export type KeyChainControllerRotateResponses = {
  /**
   * Key chain rotated successfully
   */
  200: unknown;
};

export type VerifierOfferControllerGetOfferData = {
  body: PresentationRequest;
  path?: never;
  query?: never;
  url: "/api/verifier/offer";
};

export type VerifierOfferControllerGetOfferResponses = {
  /**
   * JSON response
   */
  201: OfferResponse;
};

export type VerifierOfferControllerGetOfferResponse =
  VerifierOfferControllerGetOfferResponses[keyof VerifierOfferControllerGetOfferResponses];

export type StorageControllerUploadData = {
  body: FileUploadDto;
  path?: never;
  query?: never;
  url: "/api/storage";
};

export type StorageControllerUploadResponses = {
  201: unknown;
};
